### ISSUE TITLE
enhancement: item router highlight 

### ISSUE THREAD

**Issue by boneskull** [desht/ModularRouters#100]
I make liberal use of the camouflage upgrade.  And like the moron I am, I often forget where I put them.  It'd be cool to be able to highlight routers via some means.  For example, if I hold a router in my hand and sneak, it'd highlight all nearby routers in bright green.

**Comment by desht** [comment]
Yep, that had occurred to me too on occasion, it's a good idea.

**Comment by desht** [comment]
Added in 7.3.0 release
