### ISSUE TITLE
filtr checks if the item no longer exists

### ISSUE THREAD

**Issue by Natalia-Oreiro** [desht/ModularRouters#101]
Minecraft: 1.16.4
Mod: modular-routers-1.16.3-7.2.0-39

Hi, filtr checks if the item no longer exists, is there such a filter?
I only need to add one diamond to the machine at a time. (two diamonds will make different recipe)

thanks.

PS: does this mod have any Discord Server?

**Comment by desht** [comment]
Check out the Regulator Augment which allows you to put a specific limit on the number of items server or pulled. You can set it to only allow one item into the target inventory.

No discord at this time, but I might add one soon, keep an eye on the Curseforge page for a link...

**Comment by Natalia-Oreiro** [comment]
thank you it works but i still have a problem.

is it possible to set 1x any type of item?
i need to put in chest 64x Diamonds 64x Emeralds 64x Blaze rods .etc
When the "item Router" gradually sends 64x diamonds to the machine and starts sending emeraldy, the machine freze because the recipe has not been finished yet and there is one diamond and one emerald in it.

**Comment by desht** [comment]
I don't really understand what you're trying to do here.  Can you explain more clearly what it is you're trying to achieve, which machine(s) you're using etc.?

**Comment by Natalia-Oreiro** [comment]
ok, i have 64x Diamonds 64x Emeralds 64x Blaze rods.
and using the machine: Energizing Orb (mods: Powah)
64x Diamonds > 64x Niotic Crystal
64x Emerald > 64x Spirited Crystal
64x Blaze Rod > 64x Blazing Crystal

the problem is that the powah machine has more slots and i need to import any item one by one.

**Comment by desht** [comment]
Ah, OK.  No, the router can't really do that sort of inventory detection.  It sounds like it might be easier to have three Energizing Orbs, one for each item type...
