### ISSUE TITLE
Changing module config freezes the game

### ISSUE THREAD

**Issue by hRobert12** [desht/ModularRouters#102]
### Minecraft Version
1.16.4

### Forge Version
35.1.4

### Mod Version
7.2.0-39

### Describe your problem, including steps to reproduce it
Closing module UIs after changing their config causes the game to completely freeze.

### Any other comments?
I'm not entirely sure if this was a me problem or an actual bug with the mod. I've already tested it with just this mod and JEI.

UPDATE: The problem seems to only happen when I use my inventory key, bound to TAB.

**Comment by desht** [comment]
Confirmed, and it specifically only happens when the inventory key is bound to Tab.  Doesn't happen with the default 'E' binding.  There's a conflict with the mod's use of Tab in GUI's to cycle through textfields in the current GUI.  Should be easy enough to fix, I think.

**Comment by desht** [comment]
Fixed in 7.3.0 release
