### ISSUE TITLE
Stack upgrade - info

### ISSUE THREAD

**Issue by 648643579** [desht/ModularRouters#104]
modular-routers-1.16.3-7.2.0-39.jar

Hello, what is the difference when I have a stack upgrade in a modular router + another upgrade in a "Puller Module" ?
https://i.imgur.com/CLlLczp.png

does it somehow count together?

**Comment by desht** [comment]
No, stack augments in the module override any stack upgrades in the router.  That's documented in the Patchouli manual page for the stack augment.
