### ISSUE TITLE
Regular expression filter says it matches display name, not registry name

### ISSUE THREAD

**Issue by PORTB** [desht/ModularRouters#108]
### Minecraft Version
1.16.4

### Forge Version
35.1.13

### Mod Version
1.16.4-7.3.0-47

### Describe your problem, including steps to reproduce it
The help tooltip (accessed by pressing 'i') of the regex filter says that it matches on display name, when it actually matches registry name. The tooltip should be changed to say that it matches on registry name.

**Comment by desht** [comment]
Fixed in 7.3.1 release
