### ISSUE TITLE
[1.16.4] Block Villager Interactions

### ISSUE THREAD

**Issue by NielsPilgaard** [desht/ModularRouters#109]
### Minecraft Version
1.16.4

### Forge Version
1.16.4-35.1.36

### Mod Version
modular-routers-1.16.4-7.3.0-47

### Describe your problem, including steps to reproduce it
It's possible to "lock" a villager, making the player unable to open the villager GUI. Reloading the world fixes the villager.
Steps to reproduce: https://streamable.com/3nh4vz

### Any other comments?
Original report: https://github.com/NillerMedDild/Enigmatica6/issues/853

**Comment by desht** [comment]
I guess this should apply to any entity which opens a GUI when right-clicking. Not sure if that can be autodetected, so a configurable blacklist (with villagers as default) might be best.

**Comment by NielsPilgaard** [comment]
I'd be happy with that solution 🙂

**Comment by desht** [comment]
That's in build 48 if you feel like testing :)

**Comment by desht** [comment]
Fixed in 7.3.1 release
