### ISSUE TITLE
[1.16.4]I hope regex filter can support Chinese

### ISSUE THREAD

**Issue by Gan-N** [desht/ModularRouters#111]
### Minecraft Version
1.16.4
### Forge Version
35.1.36
### Mod Version
7.3.0-47
### Describe your problem, including steps to reproduce it
Regex Filter Can't match items that are translated into Chinese by I18N

https://user-images.githubusercontent.com/35490649/104830331-d1156880-58b8-11eb-959b-eff016a7983d.mp4

**Comment by desht** [comment]
The regex filter now works on the item registry name, not the translated display name. Use F3+H to show the registry name.
