### ISSUE TITLE
Filter bugs

### ISSUE THREAD

**Issue by hanxiaoxin778** [desht/ModularRouters#112]
### Any other comments?

Sorry, my English is not good。

In RegexMatcher.java ,

String name = stack.getItem ().getRegistryName().getPath();

In the game, coal ore is "minecraft:coal_ore",But the name is coal,

And the stone in the game is "minecraft:stone" But the name is cobblestone.

So it doesn't work.

In simpleitemmatcher, coal and red stone and minerals seem to be indistinguishable in the game，It seems to have something to do with silk touch。

Game version 1.16.4 mod version 1.16.4-7.3.0-47,

I hope I can express myself correctly.

**Comment by desht** [comment]
In what module are you using this filter?  A Breaker Module?  It matches against the *dropped item* name, not the block name.  So if the Breaker Module doesn't have Silk Touch, you should match against the item that is dropped. 

This is intended behaviour, not a bug.

**Comment by hanxiaoxin778** [comment]
I see. Thank you very much！！！
