### ISSUE TITLE
[1.16.4] Compatibility problem with chisels and bits

### ISSUE THREAD

**Issue by mmis1000** [desht/ModularRouters#116]
### Minecraft Version
1.16.4
### Forge Version
35.1.36
### Mod Version
1.16.4-7.3.1-50
### Describe your problem, including steps to reproduce it
Put stitched `chisels and bits` blocks in to extruderII with mimic argument cause client crash
https://paste.ee/p/KGqbp
### Any other comments?
Issue opened on `Chisels-and-Bits ` 's side: https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/610

**Comment by mmis1000** [comment]
The save https://drive.google.com/file/d/1R2kAHKdFkxvpt7QEKX551Ec8d31Fcs2B/view

The broken block:
Block location: World: (39,70,-833), Chunk: (at 7,4,15 in 2,-53; contains blocks 32,0,-848 to 47,255,-833), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)

There is a buggy tile near by entity that  will crash the client/server

**Comment by desht** [comment]
Both mods have "camo" functionality, where the block/TE holds a camo state.  Unfortunately this means they end up in a infinite loop asking each other what light level the blockstate should have.

I've add a blacklist in my template frame blocks to not request a mimic'd light level for C&B chiseled blocks, which hopefully fixes the issue.  You can test this with build 51 from https://jenkins.k-4u.nl/job/Modular%20Routers%201.14+/

**Comment by mmis1000** [comment]
Seems that workaround works, no longer crash
(Edit, turns out not reproduce the bug correctly)

**Comment by mmis1000** [comment]
https://paste.ee/p/ARRMQ
Doesn't seems to do the job.
Still crashes with build 51

BTW.
However I managed to patch up it with a reentry guard, and seems works (for me).
https://github.com/mmis1000/ModularRouters/commit/dd57aa6fe31fa0a45c781b86e88b61cadf9d9323

**Comment by desht** [comment]
OK, I'm making a couple more changes which should actually fix this, although only by not supporting C&B blocks in the Extruder Mk2 or as Router camo (camouflage upgrade).  Neither really work properly (actually, C&B blocks seem to have all sorts of rendering problems for me right now, separate from Modular Routers).

So I'm blacklisting all C&B blocks from the Camouflage Upgrade and also from use in the Extruder Mk2.  It's the only way right now to ensure stability.  I'll review again in future when C&B on 1.16 is more mature.

**Comment by desht** [comment]
BTW, the RunShallow hack is clever, but I don't plan to include in the mod.

**Comment by desht** [comment]
Worked around in 7.4.0
