### ISSUE TITLE
[Suggestion] Terminate additional option

### ISSUE THREAD

**Issue by bronsonty** [desht/ModularRouters#117]
**Suggestion:**
I would like the option to terminate when item in buffer is not used.

**Background:**
I am currently doing a modded play through where I am not using any mods that require RF. As such, Modular Routers has been very beneficial to simplifying my logistics. Currently I am in the process of going through my system and reducing the number of routers I am using to reduce the amount of lag I am generating so that I won't have any problems in the future. 

**Reason for suggestion:**
Currently I am working with a small kelp farm that has a single furnace to turn some of it into dried kelp. This is where I ran in problem. In order to run the furnace I am currently using 3 routers to prevent the system from jamming. With the above suggestion I would be able to reduce it to a single router. This would give it better functionality similar to redstone (ignore , run on high, run on low type of thing).

Thank you for your time.

**Comment by desht** [comment]
I've actually considered that in the past. Good to know that someone has come up with a practical application for it...

**Comment by desht** [comment]
Added in 7.4.0.  Termination button on modules is now a tri-state.
