### ISSUE TITLE
Router unable to place or break blocks in clamed chunks

### ISSUE THREAD

**Issue by Ferinheight-451** [desht/ModularRouters#118]
### Minecraft Version
1.16.4
### Forge Version
35.1.36
### Mod Version
ATM6
### Describe your problem, including steps to reproduce it
The modular router will not place or break blocks when I place it in my clamed chunk. I exit the clamed chunk and it will break/place blocks. If this is intended to work this way, could the security upgrade have a check box to allow/disallow this function?

**Comment by UnleashedEkko** [comment]
Same problem with the Minecolonies borders.

**Comment by desht** [comment]
The router's fake player is called `[Modular Routers]` with a UUID of `93d3a9c0-dfdc-36fd-9405-cb6289d20999`.  You should be able to use those in your chunk claiming mod configuration to permit the routers.  If you're using FTB Chunks, then I know it works if you add the `[Modular Routers]` fake player (I tested today).

The next release of Modular Routers will have a feature whereby a Security Upgrade will make the router's fake player work as the Security Upgrade owner, meaning that if you own the upgrade and put it in your router, the router will work with your playername and ID, so any protected chunks you have access to will also be automatically accessible by that router.

**Comment by Ferinheight-451** [comment]
Thank you for your response.
