### ISSUE TITLE
Breaker Module voids broken anvil

### ISSUE THREAD

**Issue by csonyi** [desht/ModularRouters#120]
### Minecraft Version
1.16.4

### Forge Version
forge-35.1.37

### Mod Version
modular-routers-1.16.4-7.3.1-50

### Describe your problem, including steps to reproduce it
I palced a modular router with a breaker upgrade (iron pick), placed an anvil in front of it.
The router broke the anvil, but no item dropped.
A breaker module with a diamond pick produced the same result.

### Any other comments?
This happened in Enigmatica 6 - E6.

**Comment by csonyi** [comment]
After some more testing, I found that every block breaker has the same effect, not just yours. Sorry for jumping to conclusions before actually doing some actual testing :D

**Comment by desht** [comment]
I think this is possibly due to some other mod in the E6 pack messing with anvil-breaking in general.  In my test world, I found the router picked up the anvil as an item, as expected.
