### ISSUE TITLE
[Thank you!] no issues :)

### ISSUE THREAD

**Issue by vakermit** [desht/ModularRouters#121]
Let me just say thank you!

This is a cool mod and has all the features already.

I was gong to ask if sneak clicking a filter on an inventory would match the items from it

but it does that already !!!

I was getting confused with all the separate modules. so I thought to ask can you rename modules them on an anvil

But it does that already !!!

Only minor suggest, or i just have not figured out how to do it. is ability to clear a filter by sneak clicked on air.

Thank you again for a fun and fabulous mod!

**Comment by desht** [comment]
Glad you like it! You should be able to reset any module to default settings by crafting it with itself in a crafting grid.
