### ISSUE TITLE
[Suggestion] Lore Filter

### ISSUE THREAD

**Issue by jackwright-ual** [desht/ModularRouters#122]
Just an idea, could be interesting to sort through mob drops with lores

**Comment by desht** [comment]
Problem with that is lore is a client side thing, and the search logic runs on the server (which can't know what language the client player is using).  I agree it would be useful, but not sure it's practical...

**Comment by jackwright-ual** [comment]
> Problem with that is lore is a client side thing, and the search logic runs on the server (which can't know what language the client player is using). I agree it would be useful, but not sure it's practical...

Quick reply - thanks, you could possibly use the lore translate key

**Comment by desht** [comment]
There's no such thing as a "lore translate key".  Any lore (i.e. tooltips) that are added to an item are done client-side by mods.  The only translation key is for the item's display name.

**Comment by jackwright-ual** [comment]
Created my own filter named "NBT Regex Filter"

```
   @Override
    public boolean matchItem(ItemStack stack, Filter.Flags flags) {
        if (stack.isEmpty()) return false;
        
        //check tag exists
        if(stack.getTag() == null) {
        	return false;
        }

	    for (Pattern pat : patterns) {
	      	String nbtData = stack.getTag().getString();
	        if (pat.matcher(nbtData).find()) {
	            return true;
	        }
	    }
        return false;
    }
```
