### ISSUE TITLE
Routers and Wither Skeleton Skulls

### ISSUE THREAD

**Issue by papaworld** [desht/ModularRouters#123]
MC 1.16.5
FML 36.0.46
Modular Routers: 1.16.4-7.3.1-50

Hi, in 1.15.2, made a successful build with modular routers forming a wither with soul sand and skulls. In 1.16.5, the skulls will not place correctly. Tried look level, up and down. So, I did a test with only two routers. The first router to activate placed the skull correctly, the second did not. It would place the skull against the first skull and not the soul sand. Went back to three routers, activated router 1 and 3... worked. Activated 2 didn't place properly. Flip it around, activated 2, placed properly. Activated 1 and 3, both did not place correctly.

Would it be possible that this "feature" be implemented in 1.16.5, as in 1.15.2?

Thank you

**Comment by desht** [comment]
Why are you even using activator modules for this?   Placer modules work fine and are the intended way to *place* wither skulls.

In any case, 7.4.0 (not released yet) has a rework of the activator module and I just tested placing skulls with it, and it works there.

But use the placer module for placing blocks. It's what it's there for :P

**Comment by papaworld** [comment]
The placer module worked fine. The activator module allows for distance placing of 3 or 4 blocks... can't remember. Makes for a less cramped spawner build. The activator module also allowed for "nicer" redstone signalling build feeding item routers from under the floor, of soul sand first, then skulls for both auto repeating and manual one-time without item router activation for soul sand and skulls from xmitting to each other without the need for the redstone override addon.
