### ISSUE TITLE
Bulk Item Filter dupe

### ISSUE THREAD

**Issue by AdamYellen** [desht/ModularRouters#124]
### Minecraft Version
1.16.5

### Forge Version
36.0.46

### Mod Version
1.16.4-7.3.1-50

### Describe your problem, including steps to reproduce it
Open the Bulk Item Filter interface and rapidly left-click an item into an available slot.

**Comment by desht** [comment]
I'm not seeing any item duping happening here.  Please explain further.

**Comment by AdamYellen** [comment]
Server environment with Sky Bees modpack (version "final"). A video showing the behavior can be seen [here](https://take.ms/NpNDk).

**Comment by desht** [comment]
Fixed in 7.4.0
