### ISSUE TITLE
Suggestion for FE intergation

### ISSUE THREAD

**Issue by Taccio33** [desht/ModularRouters#125]
A system for a Battery-like item to buffer energy that could be this way wirelessly transmitted and\or received, similar to item, liquid and xp transferring.

**Comment by desht** [comment]
I have considered something like this.  I probably wouldn't add a battery item per se (can leave that to other mods), but I might add an Energy Module which can push energy to adjacent blocks (and a Mk2 with push FE wirelessly within a certain range).

**Comment by Taccio33** [comment]
Thank you!

**Comment by ManiacRobertWasTaken** [comment]
If you will change your mind about this, i will suggest adding a Distributor Module like items one.

**Comment by desht** [comment]
Next release (7.5.0) has greatly expanded energy support, including an Energy Upgrade to give the router its own energy buffer, and Energy Output and Energy Distributor modules to push energy to adjacent or nearby blocks.

If you want to test a dev build, try build 57  from https://jenkins.k-4u.nl/job/Modular%20Routers%201.14+/ (usual disclaimers apply, back up your worlds, don't use on a production server etc...)

**Comment by Taccio33** [comment]
Thank you, going to test the new features right now!

**Comment by Taccio33** [comment]
The energy distribution module seems like the perfect upgrade (even if it's more of a energy module mk2) but in testing seems to not work on some blocks that have FE inputs. Am I missing something? Should the reciving end be a battery or something like that or is this just a bug? 
Edit: It actually works on some things, but on some it doesn't. To be more precise what I mean by not working: when I shift right click it doesn't select a block. the blocks on witch it doesn't work roght now are: harvesters in general from spatial harvester
extreme cobblestone generator from ecg mod
every powered block from cyclic

**Comment by desht** [comment]
Yeah, think I know why that is.  Easily fixed...

**Comment by desht** [comment]
Build 58 should fix that

**Comment by Taccio33** [comment]
Now it works, thanks!

**Comment by desht** [comment]
Added in 7.5.0
