### ISSUE TITLE
Player stuck on module's GUI

### ISSUE THREAD

**Issue by Scheigster** [desht/ModularRouters#127]
### Minecraft Version
1.16.5

### Forge Version
36.1.2

### Mod Version
7.4.0-55

### Describe your problem, including steps to reproduce it
If you have another player currently on a module configuration interface and you break the router it is on, your friend stays stuck on the GUI.

As a side note, I only tested the Dropper Module.

**Comment by desht** [comment]
Think I see the problem here.

**Comment by desht** [comment]
Fixed in 7.5.0
