### ISSUE TITLE
Breaker module voids Anvils

### ISSUE THREAD

**Issue by Nosmeister** [desht/ModularRouters#128]
### Describe your problem, including steps to reproduce it

Hello! Currently the breaker module breaks anvils without harvesting the item. I tested this with varying degrees of pickaxes used in the crafting recipe for the module from stone to diamond. It breaks the block but then voids it rather than pulling it into its inventory. I even tried with a pickaxe that was enchanted with silk touch.

### Any other comments?

Disclaimer, I am playing this in the ATM 6 modpack so I apologize if this is from some unforeseen mod interaction.

**Comment by desht** [comment]
This has been reported before (#120) and it's still not reproducible.  I'm sure there's some other mod messing things up here; the linked issue mentions that other block breakers also suffer the same problem, so if you have any other such breakers in your pack, can you try those too please?

**Comment by desht** [comment]
Closed due to lack of response.
