### ISSUE TITLE
Activator Module in current versions not working properly

### ISSUE THREAD

**Issue by papaworld** [desht/ModularRouters#129]
MC: 1.16.5
FML: 36.1.4
Modular Routers: 1.16.4-7.3.1.50 and 1.16.5-7.4.0.55

Reverted back to Modular Routers: 1.16.4-7.3.0.47 --- this version works correctly

Hi, the activator modules stopped working when I updated to v50 and v55. Similar problems as in Issues #95 and #123. Went back to v47 then all worked again, as intended after re-programming the activator module settings.

v50 & v55: The look-up, look-level and look-down did not work as before for fertilizing, skull placement, sapling planting, plucking bulbs (attained drops), bucket water pickup and empty, and more.... etc. As mentioned, went back to v47 all worked again.

Also, had an issue with the placer, but I need some time to get back to you on this.

Thank you.

Edit: you mentioned in issue #123 to use the placer module for skull placement, I can't get that to work either... skulls are miss-aligned... tried different setups. Would you please be so kind to inform me as to how to get this to work successfully.

**Comment by desht** [comment]
OK, you're going to need to provide precise descriptions of the scenarios you've tried which don't work.  Because everything I've tried that you mentioned works for me in the latest release.

**Comment by papaworld** [comment]
Hi, collected screenshots of the builds that cover, I believe, most of the issues. Hopefully, it is helpful to you.

1.16.1 & 1.15.2 - Wither Builder. Worked flawlessly. The Router in the floor places 4 soul sand, has 3 activator and 1 placer modules. The 3 Routers on the left place the skulls on to the soul sand using activator modules on delayed pulse. The Router on the right is xp orbs pickup producing bottles-o-enchanting. This design stopped working properly upon 1.16.3 release... the skulls would be placed upon the floor, air or skull-on-skull... mostly turned 90 degrees (this was dependent on which Router got the first tick pulse).
![1 16 1 Wither Builder](https://user-images.githubusercontent.com/50890375/117482934-b5e36d00-af2a-11eb-92d7-c00fbbb8eb84.png)


1.16.5 - a mix of things that stopped working with v50 and v55... version 47 works fine...

The left Router places the sapling, activator module level-down worked. The right Router fertilize the sapling, does not work at all at any setting. (The bucket water fill/empty works.)
![1 16 5 Sapling n Fertilizing UP](https://user-images.githubusercontent.com/50890375/117483819-db24ab00-af2b-11eb-9583-012e91f97c88.png)


In order to fertilize, the Router works when look-level is set and within its 4 block range. BTW: the Distributor modules work great.
![1 16 5 Sapling n Fertilizing LEVEL](https://user-images.githubusercontent.com/50890375/117483978-19ba6580-af2c-11eb-9eb8-f956cd35cd24.png)


1.16.5 v47 - works great with Attained Drops. Each Router has 8 activator modules. First 4 modules plant going Left-Back-Right-Front. The last 4 modules look-up to pluck the resource bulb and place these in inventory, also Left-Back-Right-Front. (Attained Drops is highlighted... it is not the only problem with Routers) The 2 Routers in the floor are breaker and placer, these work fine.
![1 16 5 v47 Attained Drops](https://user-images.githubusercontent.com/50890375/117487257-77e94780-af30-11eb-9dcb-d37b3b86dafc.png)
With v50 and v55, Ender Pearls were planted and the remainder throw into the world emptying inventory. The other resources planted correctly. None of the look-up modules worked to pluck the bulbs regardless of resource.

My take is two-fold:
1) the look-up -level -down is not working as intended, similar to issue #95. (planting, fertilizing and block placement)
2) the three settings for activator modules (furnace-dispenser, bow, entity) changed to now two settings.

With the exception of the Wither Builder.... all other modules work great... distributor, vacuum item/orb, breaker, placer, dropper, redstone detector/augment, speed, blast, range, fast pickup... etc.

As it is now, if I used v55, there would be about 26 Item Routers that would have to be removed from service in my current world, and another scheme would need to be built. This is why v47 was re-installed.

Hopefully this is helpful to you. As in issue #95, I would be more than pleased to assist you in any way possible.

Thank You.

**Comment by desht** [comment]
Bad news for you unfortunately... a lot of what your world depended on is simply behaviour that has changed in 7.4.0.  7.3.0 worked a certain way but it had its own share of problems (I didn't make the changes I made on a whim).

The logic for 7.4.0 is that the fake player's eye point is placed on the face of router that the activator module faces.  It does accurate raytracing from that point, so if a solid block is in the way, the raytrace is likely to fail.  Imagine if you yourself were right-clicking something with your eye at that precise position.  The router simulates as closely as possible what a real player would do, and see.

All of what you're trying to in the images above can still be done, but it will need a little rearrangement of routers to make work.  I won't be going back to the old behaviour, sorry.

**Comment by papaworld** [comment]
Ok, thanks for your response... the look-up, -level and -down issue on the activator will not work? ie: setting is look-down to plant a sapling, but the sapling is up.

**Comment by desht** [comment]
I'll check into that specific case.

**Comment by desht** [comment]
I just made some changes which should make the look up/down behaviour a lot more intuitive.  If you're interested in testing, give build 57 from https://jenkins.k-4u.nl/job/Modular%20Routers%201.14+/ a go.

Specifically, the router can now use "look up" mode to plant a sapling or crop on top of a solid block which is beside or on top of the router.  Same should apply to bonemealing that sapling/crop.  At least it works fine in my testing but would be good to get a second pair of eyes on it :)

**Comment by papaworld** [comment]
Your fix works fine. Is it possible to PM?

**Comment by desht** [comment]
Yeah you can message me on discord if you need to discuss something.

**Comment by desht** [comment]
Fixed in 7.5.0
