### ISSUE TITLE
Feature: Allow clearing target of push/puller modules

### ISSUE THREAD

**Issue by shabble** [desht/ModularRouters#13]
This might be possible, but I'm not sure how if so.

I accidentally set the destination for a half-stack of modules instead of just one, and although I can still re-target them elsewhere as normal, it would be nice to have a way to clear them back to empty destination/target so they will stack properly with the rest.

Usual methods for this are either placing it alone in a crafting table [ `Module (configured) -> Module (clean)`] or shift-right-clicking into the air.

The former seems less prone to accidents, but any method would be good.

MC 1.10.2
MR `modular-routers-1.10.2-1.2.5.jar`

**Comment by desht** [comment]
Yeah, that sounds reasonable.  What I'll do is add recipes for all modules to allow them to be crafted into themselves, and doing so will reset _all_ NBT on the module.  That includes stored destinations, the filter, any module settings (whitelist, match meta etc.), and any enhancements which have been added.

**Comment by desht** [comment]
Actually, since it wasn't difficult, I've added both possibilities...

- Crafting a module by itself does a full reset of all NBT, back to a newly-crafted state
- Sneak+Right-click a targetable module (Sender Mk2/3, Puller Mk2) on any non-inventory block (including air) clears its target

**Comment by desht** [comment]
Added in 1.3.0 & 2.1.0 releases, just uploaded.
