### ISSUE TITLE
are breaker modules supposed to drop xp orbs while mining ores like coal/diamond?

### ISSUE THREAD

**Issue by DoomSquirter** [desht/ModularRouters#132]
### Minecraft Version
1.16.5

### Forge Version
36.1.13
### Mod Version
modular-routers-1.16.5-7.4.0-55
### Describe your problem, including steps to reproduce it
have a placer and a breaker in two separate routers facing each other, one block in between, putting ore blocks to process that are fortunable, made a breaker with a fortune/efficiency pick.  it's mining the blocks fine, but I'm getting zero xp orb drops.

**Comment by desht** [comment]
They currently don't, although that's something I could add certainly add for 7.5.0.  Probably a good idea.

**Comment by DoomSquirter** [comment]
that's great.  thanks for responding.

**Comment by desht** [comment]
Added in 7.5.0
