### ISSUE TITLE
Missing "Round Robin Filter Augment" recipe in CurseForge jar, present in manual build

### ISSUE THREAD

**Issue by ghost** [desht/ModularRouters#133]
### Minecraft Version
1.16.5

### Forge Version
36.1.6

### Mod Version
modular-routers-1.16.5-7.4.0-55

### Describe your problem, including steps to reproduce it
1. Open JEI and click on the "Round Robin Filter" item. No recipe appears.
2. Add an Augment Core and a Clock on a crafting table. No output is given.

Using CurseForge jar:
![image](https://user-images.githubusercontent.com/83793683/122648672-d2f58900-d0ef-11eb-9a60-f85146e08492.png)

Using manual build:
![image](https://user-images.githubusercontent.com/83793683/122648675-d557e300-d0ef-11eb-9d08-f0796f3e1ba7.png)

### Any other comments?
I noticed some other files in the jar are missing or out of sync as well, but this one was the easiest to explain.

**Comment by desht** [comment]
Already fixed in 7.5.0.

**Comment by ghost** [comment]
D'oh, sorry about that. I never think to check for a beta jar.
