### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by TheTechPny** [desht/ModularRouters#134]
### Minecraft Version
1.16

### Forge Version
forge-1.16.5-36.1.32

### Mod Version
modular-routers-1.16.5-7.4.0-55.jar

### Describe your problem, including steps to reproduce it
Dupe glitch
"so basically modular routers has this item called the player module or whatever
that lets you link your inventory to it so it can pull items out of it
if you open a backpack, take the items out of it, and then get it forcefully removed from your inventory then it doesn't save properly, and the items stay in your inventory and in the backpack"

**Comment by desht** [comment]
I need a lot more information than that. For a start, which backpack?  Many mods add backpacks.

Then please provide details instructions on how to reproduce the dupe.

**Comment by desht** [comment]
Actually, thinking about this part:

> if you open a backpack, take the items out of it,

if the backpack isn't saving contents as soon as the items are removed from it, that's a bug with the backpack in question.  Not Modular Routers.
