### ISSUE TITLE
Terminate on No Match

### ISSUE THREAD

**Issue by Celebnasse** [desht/ModularRouters#138]
### Minecraft Version
1.16.5

### Forge Version
36.1.31

### Mod Version
7.5.0-59

### Describe your problem, including steps to reproduce it
A puller module (at least Mk. 1, didn't test 2 or 3), with stack upgrades in it, set to Terminate on No Match, will not continue if it doesn't pull the full number of items (based on how many stack upgrades it has).  For example, I had a module with 6 stack upgrades (so a full stack at a time).  It was set first in the line.  After it I had a detector module, then a pusher module.  If the puller didn't pull a full stack, the detector and pusher didn't ever activate.

**Comment by desht** [comment]
Confirmed.  Should be a very simple fix.

**Comment by desht** [comment]
Fixed in 7.5.1 release
