### ISSUE TITLE
 Modular Router Stops working randomly

### ISSUE THREAD

**Issue by JammerFTW** [desht/ModularRouters#14]
Im not sure if this is a bug or not, but i think it is. anyway, the item routers work for a while, and then just randomly stop, and then i have to take out a module for them to start up again, only to stop a few minutes later.
Please fix this as this is really annoying.

Thanks!

Modular Routers Version: 1.3.0

**Comment by desht** [comment]
I haven't been able to reproduce this at all, so I'm going to need a lot more info:

* What is the configuration of your router?  I.e. what modules are in it, how are they configured, what inventories are they working on, what's in the buffer, what's the redstone setting of the router...?
* Is there any stack trace when the router stops running?
* Is the area chunk loaded?  Does the router stop if the chunk is unloaded then reloaded?  (I've tested for this and can't see a problem with it, but it may be related)

**Comment by desht** [comment]
Closing due to lack of feedback.
