### ISSUE TITLE
[1.16.5] Regulator Augment Issue

### ISSUE THREAD

**Issue by kjj194** [desht/ModularRouters#140]
### Minecraft Version
1.16.5
### Forge Version
1.16.15-36.2.1
### Mod Version
1.16.5-7.5.0-59
### Describe your problem, including steps to reproduce it
Regulator Augment on a puller turns on when it hits the required amount but will continue to pull after the amount of items in the target inventory have fallen below the specified level. 
### Any other comments?
![image](https://user-images.githubusercontent.com/5005560/129470386-52b3d12d-b936-483c-9bd4-decc61c570ed.png)
![image](https://user-images.githubusercontent.com/5005560/129470389-ccde8046-5adb-47a1-ab6f-d0be71ab14f8.png)
![image](https://user-images.githubusercontent.com/5005560/129470435-063123a9-cb21-4aed-8f23-4b1ca11b8c83.png)
![image](https://user-images.githubusercontent.com/5005560/129470444-4fc6fc03-24d9-4bd7-a615-8dbee5ec6c17.png)

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Fixed in 7.5.1 release
