### ISSUE TITLE
Activator does not attack villagers and wandering traders.

### ISSUE THREAD

**Issue by jebjordan** [desht/ModularRouters#141]
### Minecraft Version
1.16.5

### Forge Version
36.2.0

### Mod Version
modular-routers-1.16.5-7.5.1-69

### Describe your problem, including steps to reproduce it
The activator module when in attack entity mode will not attack wandering traders or villagers.
I assume this is somehow a byproduct of the entity right-click blacklist that was introduced. It shouldnt be blocking attacking them though.

If you could, please fix this behaviour. I expect it to attack any entity within range, as it is configured to do so.

Steps not exactly necessary but here:
1) place down router,
2) put in an activator module
3) set it to attack entity mode.
4) spawn a villager or trader.
5) Expecting them to get hit by your sword or whatever you put in the router? nah, they're fine.

### Any other comments?
Another side note, from what I can tell there is currently no way to filter what entities get attacked by the module in the attack mode.

**Comment by desht** [comment]
Yes, you're right - the same blacklist is actually used, though it probably shouldn't be for attacking.

What I'll do is add a second configurable blacklist - "activatorEntityAttackBlacklist" - to be used for attacking.  The existing "activatorEntityBlacklist" will only be for right-clicking entities.

**Comment by jebjordan** [comment]
Thanks. I assume this second blacklist will be empty then. Alrighty then. 

Thanks for the reply and have a great day!

**Comment by desht** [comment]
Yep, it will be empty by default.

**Comment by jebjordan** [comment]
Just a quick question, how long before the next update is released? It's been 2 months so just wondering. @desht 

Thanks in advance!

**Comment by desht** [comment]
Sorry, RL commitments are a thing at the moment. Hopefully fairly soon.

**Comment by jebjordan** [comment]
Thanks for the response. No worries!

**Comment by desht** [comment]
Fixed in 7.5.2 release
