### ISSUE TITLE
Feature Request: Sidedness Augment.

### ISSUE THREAD

**Issue by ghost** [desht/ModularRouters#144]
Some machines (such as from Mekanism) need to be set up so that they accept certain items from specific sides, and output results to specific sides.

It would be helpful if there were a sided augment so that a sender module could attempt to insert to a particular side of a block, and a puller module could attempt to remove items from a particular side.

**Comment by desht** [comment]
Sender and puller MK2 modules already do this. When you click the module on the block to set its target, the clicked side is used.

**Comment by ghost** [comment]
That doesn't appear to be documented anywhere in the manual for the mod.

**Comment by desht** [comment]
The in-world highlight cube shows the selected side in a different colour, and the selected side is in both the feedback message you get when the block is selected, and in the item tooltip.

If that's still not clear enough, I guess I can add some text to the manual too...

**Comment by ghost** [comment]
I'm color blind, so anything conveyed entirely by color change is lost on me.

**Comment by ghost** [comment]
And, I have to admit, I'm one of those folks who read the manual rather than just trying random stuff. If it doesn't mention a capability in the manual, I move on. I don't go checking to see if the author left something out.

**Comment by desht** [comment]
Actually, color is the wrong phrase to use here.  The highlight box is drawn mostly transparent, but the selected side has a higher alpha, i.e. it's a lot more opaque than the other 5 squares which are drawn.
