### ISSUE TITLE
Detector modual ignoring redstone mode

### ISSUE THREAD

**Issue by NJM1564** [desht/ModularRouters#150]
### Minecraft Version
1.16.5
### Forge Version
36.2.4 (I think. FTB launcher doesn't make it easy to tell. Fortunately I might know just enough to be able to find it be looking in the .json files.)
### Mod Version
modular-routers-1.16.5-7.5.1-69
### Describe your problem, including steps to reproduce it
The detector modal continuously emits a redstone signal when an item is placed in the slot regardless of the sitting of the modular routers redstone mode or whether or not the module is receiving a redstone signal. 

The function I'm working twards is a camouflaged redstone wiring threw Xnet to Mod grinding utilities fans. Xnet won't directly conect to the fans without a redstone proxy and that can't be camouflaged so I am using the routers as proxes instead.

Using the response from another thread I used a redstone modal and with the routers main setting is set to always it works as I intend. So I have a workaround but I don't think this is supposed to be needed.

**Comment by desht** [comment]
Fixed in 7.5.2 release
