### ISSUE TITLE
XP Vacuum Augment not working with Clumps mod

### ISSUE THREAD

**Issue by raxkin** [desht/ModularRouters#152]
### Minecraft Version
1.16.5
### Forge Version
36.2.9
### Mod Version
modular-routers-1.16.5-7.5.1-69
### Describe your problem, including steps to reproduce it
Using the mod "Clumps" the xp orbs will be merged to reduce lag, and some orbs that are marged fast will not be collected by the XP Vacuum Augment. 
I'm using Clumps version 6.0.0.27 (https://www.curseforge.com/minecraft/mc-mods/clumps)

### Any other comments?
There is any plan to make them compatible?

**Comment by desht** [comment]
I'll take a look at this. If it's possible to do without adding a load of special-case code, then sure (looking at the Clumps code, I think it should be possible to do)

**Comment by desht** [comment]
So I did some testing, and Clumps orbs definitely *are* absorbed by the router with a vacuum module (confirmed with the debugger - I can see `EntityXPOrbBig` from Clumps in the list of xp orbs the router finds).

Not sure why it isn't working for you, only possibility might be that some orbs might be simply too large to absorb at once?  Just make sure you have a large enough tank in or beside the router to take all the XP fluid that the orb contains.
