### ISSUE TITLE
Crash on world load in 1.18.1

### ISSUE THREAD

**Issue by aAndrew3030** [desht/ModularRouters#154]
1.18.1
Forge 39.0.59
9.0.1-79

I am experiencing existing worlds crashing on world load. New world load fine, and I am able to load existing worlds when I remove modular routers.
[crash-2022-01-23_12.04.48-server.txt](https://github.com/desht/ModularRouters/files/7920977/crash-2022-01-23_12.04.48-server.txt)

**Comment by desht** [comment]
Yeah, current release isn't compatible with current Forge (it's a fast moving target right now).  Next release will be.  Out in a day or two, hopefully.

**Comment by desht** [comment]
Fixed in 9.0.2 release
