### ISSUE TITLE
[Feature Request] Add a module that can send redstone signals remotely

### ISSUE THREAD

**Issue by changhe3** [desht/ModularRouters#155]
Maybe Detector Mk2?

**Comment by desht** [comment]
This is a lot harder than it might appear, since there's no simple way of making an arbitrary block position emit redstone (Minecraft just doesn't work that way - redstone can only be emitted by blocks which are specifically coded to emit redstone).

**Comment by changhe3** [comment]
@desht Maybe use something like the Redstone Proxy block in XNet?

**Comment by desht** [comment]
I've given this some thought and decided against adding this.  It's just a little too out of scope for this mod, sorry.
