### ISSUE TITLE
[1.16.5] Distributor and Breaker Module Question

### ISSUE THREAD

**Issue by papaworld** [desht/ModularRouters#157]
MC 1.16.5
FML 36.2.20
Modular Routers 7.5.3-86

DISTRIBUTOR: does a SINGLE Distributor Module have the ability to target an inventory more than once? In other words... could it distribute to inventory A multiple times and inventory B once... or something like that? Did not find this module on your Wiki.

BREAKER: when the Router inventory is full the Breaker continues to break. Is there something I'm missing or is this normal? I've been using a comparator to stop the Router for now.

Thank you for creating and updating your mod. Super! Very useful... making the nearly impossible, possible.

**Comment by desht** [comment]
Hi, glad you're enjoying the mod. To answer:

1) No, a distributor can't target the same inventory twice, sorry. I guess you're trying to weight the distribution to favour one inventory in a ratio? That would need a series of senders.
2) Yes, the Breaker is intended to carry on breaking if the buffer is full. The buffer is really just a buffer, the intention is to keep it clear by sending items out as they're broken. But a comparator to pause the router is a valid approach too.
