### ISSUE TITLE
Drag from JEI support for Bulk Filters

### ISSUE THREAD

**Issue by MuteTiefling** [desht/ModularRouters#168]
### Describe the feature

This very handy feature works in regular filter slots in modules, but doesn't appear to work in Bulk Filter slots. Would be a wonderful addition. 

### Reasons why it should be considered

Ease/simplicity of setting up new filters

### Additional details

<3

**Comment by desht** [comment]
Yeah not sure why I overlooked that 😀

**Comment by Attack8** [comment]
oh ok! I was coming here to report this same thing, but it looks like it's fixed in dev so thanks! Is it ok if I make a pr for backporting this to 1.18.2? Would really like to have it in the Vault Hunters Modpack.

**Comment by radimous** [comment]
this issue is fixed in 1.18 branch in version 9.1.2, but this version is not on curseforge
could you release it on cf, so it could be included in the vault hunters modpack?

**Comment by desht** [comment]
There's a CF release now: https://www.curseforge.com/minecraft/mc-mods/modular-routers/files/4984984

**Comment by Attack8** [comment]
Great, thanks!
