### ISSUE TITLE
Modular Router compat with Bedrock Ores

### ISSUE THREAD

**Issue by Raidobw2** [desht/ModularRouters#169]
### Describe the feature

Bedrock Ores https://www.curseforge.com/minecraft/mc-mods/dadobug1111s-bedrock-ores-forge is a mod that adds infinite ores to the game.

Currently, the breaker module from Modular Routers breaks the block. I would like to suggest allowing some tag or checking for that mod's tag so that bedrock ores (or if custom tag, any block), can be prevented from breaking and being replaced with air.

### Reasons why it should be considered

Players should not be able to mine bedrock-like materials and this adds value to Modular Routers so it can be used to farm those ores instead of opening a path to the void

### Additional details

Relayed from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1062

Also reported to Bedrock Ores at https://github.com/dadobug1111/DadobugBedrockOres/issues/10

![image](https://user-images.githubusercontent.com/17010632/177884055-eb902792-fa54-466c-963b-84c4ca39408b.png)

**Comment by desht** [comment]
If Modular Routers is able to break the block, then the block isn't unbreakable.  Maybe Bedrock Ores is using some trickery to cancel a break, but the block needs to have a negative `destroyTime` to be properly unbreakable (like vanilla Bedrock or Ender Portal blocks do).  And it's clear that this fake bedrock doesn't have a negative `destroyTime`.

I don't plan to make any changes to Modular Routers for this, sorry. This is on Bedrock Ores to fix.  (Yes, I *could* add a kludge to MR, but that's the wrong way to do it.  And any other mod with a block breaker would also have to adjust for this too.  Bedrock Ores is the mod adding a block with weird behaviour; it's on it to play nice with other mods).

**Comment by Raidobw2** [comment]
I see you commented as well on the linked issue. Thank you very much for the comments and explanation, I hope the mod author from Bedrock Ores will be able to figure out a solution with your insight 😄 
Have a good weekend!
