### ISSUE TITLE
Fake player name ?

### ISSUE THREAD

**Issue by sintaxcz** [desht/ModularRouters#17]
Hello i need help i use grief prevention and players need to set /trust "player name" for item routers becouse routers cant place blocks without /trust in claims :(

**Comment by desht** [comment]
I'm using "[Modular Routers]" as the fake player name.  Is this all the info you need?

**Comment by sintaxcz** [comment]
Yes thanks and clasic UUID ? (like 00000000-0000-0000-0000-000000000000 is needed for sponge)

**Comment by desht** [comment]
93d3a9c0-dfdc-36fd-9405-cb6289d20999

(which is the result of running ``UUID.nameUUIDFromBytes("modularrouters".getBytes())``
