### ISSUE TITLE
[1.12.2] Strange mod incompatibility with Energy Control

### ISSUE THREAD

**Issue by xJon** [desht/ModularRouters#170]
### Describe the bug

Trying to hide the HUD when pressing `F1` causes visual glitches.

https://user-images.githubusercontent.com/8945347/181641942-64f58e90-f534-4057-95c6-8bc68197a287.mp4

### How to reproduce the bug

Install the latest version of Modular Routers & [Energy Control](https://www.curseforge.com/minecraft/mc-mods/energy-control/files/all?filter-game-version=2020709689%3A6756) for Minecraft 1.12.2.
Press `F1` to hide the HUD.

### Expected behavior

HUD being hidden without the color glitching.

### Additional details

I understand version 1.12 of the mod is unsupported, but if there's some sort of idea what could cause this (e.g. some config change I could make) it'd really help!

### Which Minecraft version are you using?

1.12 - UNSUPPORTED

**Comment by desht** [comment]
As you already pointed out, 1.12 is totally unsupported.  Also, Modular Routers does nothing with the HUD.
