### ISSUE TITLE
Activator module not work in my house

### ISSUE THREAD

**Issue by Jly4** [desht/ModularRouters#173]
At some point my routers stopped working. I began to try to destroy them and install them again, changed modules, settings, but nothing helped. Then I tried to put one of the routers in another dimension and it started working. Then I flew away from my house to unload it and put the router there and it also started working. Reloading the world doesn't help. Other modules seem to work fine

**Comment by desht** [comment]
Sounds to me like you have some kind of chunk protection going on.  Nothing else would simply stop an activator module working like that.

However, you haven't supplied enough information to get any idea of what your setup is.  A detailed description (screenshots useful) would help there...

**Comment by Jly4** [comment]
Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_292, AdoptOpenJDK
	Forge: net.minecraftforge:36.2.34



I made an auto-charm based on this guide https://imgur.com/gallery/FSIsYE6. At first everything worked, but once again when I needed books, I noticed that the routers with the activator module stopped working. I play single player
i make video https://disk.yandex.ru/i/brxn_5Dmzg9quQ

**Comment by Jly4** [comment]
@desht 
I found the cause of the error, the minecolonies mod within the colony's possessions did not allow interaction mechanisms to work when colony protection in world config enabled. Thanks for the tip with chunk protection
