### ISSUE TITLE
Refined Storage autocrafting and JEI autofilling in an RS crafting grid not working with module crafting

### ISSUE THREAD

**Issue by Nevrai** [desht/ModularRouters#174]
### Describe the bug

Crafting modules whose recipes include other modules don’t work with [Refined Storage](https://www.curseforge.com/minecraft/mc-mods/refined-storage) autocrafting and autofilling the recipe with [JEI](https://www.curseforge.com/minecraft/mc-mods/jei) whilst using a Refined Storage crafting grid.

For instance, let’s say I want to autocraft a sender module mk2. Even with all the materials in my Refined Storage storage—an ender pearl and four sender module mk1s—it thinks that I don’t have any, and it’s only able to autocraft two of them. The other two can’t be autocrafted, for whatever reason. The same issue occurs with other modules that use other modules in their crafting recipes as well.

![Modular Routers bug](https://user-images.githubusercontent.com/59761487/186799610-bb6b23f9-1674-48b6-b945-05e6a6424529.png)

If I hover over the autofill button (plus button) when looking at the sender module mk2 recipe in JEI whilst I’m using my Refined Storage crafting grid, it thinks I have only two sender module mk1s in my storage, even though I actually have four, and when pressing the autofill button, it won’t put any of the sender module mk1s in the crafting grid at all. I’m fully able to craft the sender module mk2 manually if I do so, but autofilling the module recipes with JEI in the Refined Storage crafting grid or autocrafting the module recipes with Refined Storage does not work.

I did clear all the modules by crafting them with themselves to make sure they have no NBT data, but the issue occurs regardless. I also tried disabling “exact” mode for the crafting patterns, but that didn’t work either. Not being able to autocraft modules or autofill the recipes in the grid makes crafting Modular Routers modules pretty tedious, so I hope this is something you can fix. I assume it has something to do with NBT data. Even though my modules’ NBT data are empty, something must be wrong with how the recipes are set up.

### How to reproduce the bug

1. Create a Refined Storage crafting pattern for a Modular Routers module that uses another module in its recipe (e.g., sender module mk2).
2. Request the module to be autocrafted.

And:

1. Open your Refined Storage crafting grid and make sure you have the required modules and other materials for a module recipe that uses another module in its recipe (e.g., sender module mk2).
2. Autofill the recipe with JEI.

### Versions

* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (0.4.29 [latest])
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Modular Routers:** 9.1.1-93 (latest for 1.18.2)
* **Refined Storage:** 1.10.3 (latest for 1.18.2)

**Comment by desht** [comment]
TBH that's something RS needs to sort out. It most likely is NBT-related, but the shapeless recipe for making Sender Mk2's just requires 4 Sender Mk1's, and says nothing about the NBT on the items; it's RS that is imposing restrictions based on the item NBT.

This is supported by the fact that JEI has no problem inserting the ingredients into a vanilla crafting table, and also an AE2 pattern terminal (AE2 does require the Item Substitutions button to be checked, but that's expected).

It's on RS here to be more accepting of NBT variations on the recipe ingredients, especially when the recipe makes no mention of NBT, i.e. when the only item is specified, the NBT doesn't matter.

**Comment by Nevrai** [comment]
All right, I have reported this bug [on Refined Storage’s issue tracker](/refinedmods/refinedstorage/issues/3363).
