### ISSUE TITLE
Put Pickup Delay Augment in Vacuum Module

### ISSUE THREAD

**Issue by Benny-Boo** [desht/ModularRouters#176]
### Describe the feature

Just allow the pickup delay augment to make the vacuum slow down.

### Reasons why it should be considered

 I was trying to put the pickup delay on a vacuum module for something and was surprised to find I couldn't cause i honestly can't think of what else it would be on lol

**Comment by desht** [comment]
Pickup Delay augments are for the Dropper & Flinger Modules, to increase the time before which players can pick up items dropped by those modules.

If you want to slow down a Vacuum Module, slow down the router (1 op per second normally, but you can put the router in pulsed mode and use an external redstone clock).
