### ISSUE TITLE
[Feature Request] Explicit Tag Filter

### ISSUE THREAD

**Issue by theboo** [desht/ModularRouters#187]
### Describe the feature

Currently mRouters has no was to filter for a specific tag, there is only the "match tags option". 

In modern modded Minecraft, mod devs are finally starting to use tags to their advantage(which is great), but this means there are a *lot* more shared tags making this feature almost useless.

Either a brand new tag filter or an option to select a tag(or tags) in the inspection filter would be amazing.

Also it was discussed in the discord to add compat with create's attribute filter. This would be fantastic, but would also be great to have an attribute filter equivalent in mRouters directly(this would cover tag filtering as well, and might be a great addition to the inspection filter)

### Reasons why it should be considered

Covered in description.

**Comment by desht** [comment]
Tag Filter is now a thing.
