### ISSUE TITLE
Clear Energy Distributor Module (or any of them) 

### ISSUE THREAD

**Issue by jdbhkf** [desht/ModularRouters#188]
### Describe the feature

It would be nice to have a key or something to be done that would clear all settings on a module. Wrench or really anything.

### Reasons why it should be considered

I setup a laser base or crafting base and move things around. I tear it down to adjust or move and forget to unlink all the connections. It basically is a huge inconvenience or bricks the module.

**Comment by desht** [comment]
Just do a self-craft with the module, that resets it.
