### ISSUE TITLE
Suggestion:  Chisel Intergration

### ISSUE THREAD

**Issue by AnthonyKane5528X** [desht/ModularRouters#19]
I don't know if this will be possible but I figured I would suggest it.

Do you think you can make the Camouflage upgrade work with blocks from "Chisel"

I'm asking for this support because Modular Routers is quickly becoming the replacement for the old Tinker's construct drawbridges.  I tested out a Modular Router with a wood block from Chisel and it didn't render the Router at all.  Instead the block went transparent.

Anyway, like I said this is a suggestion for Chisel (not Chisels & Bits) support.

Thanks.

**Comment by GreatOrator** [comment]
Actually, chisel & bits integration would be awesome as well.  Routers seem to not be able to store the NBT when using the MKII module for placing and picking up (and MKI can't pick up once placed)

**Comment by desht** [comment]
Both Chisel and C&B integration are something I'd like to add and have looked at in the past, without success so far.  So I'm not saying never, but both are things that will need more research (and time, which is limited, unfortunately)...

**Comment by AnthonyKane5528X** [comment]
@desht 
-If it would help at all, Boni (the dev for Tinkers2) has stated the the code is open.  Perhaps taking a look at the "old" Tinker's Construct/Mechworks code, with regards to the drawbridge may help you figure out how that block handled it, since it was able to use "Chisel" (not C&B) blocks in its inventory.

**Comment by desht** [comment]
Unlikely - 1.7.10 block rendering is utterly different from 1.10.2 rendering.  No chance of drawing any comparisons at all there.

**Comment by GreatOrator** [comment]
If it helps, the basic module can push out the proper C&B block, just not pick it up, the advanced one turns them into block frames, so wager it is something to do about the NBT that is stored (though you probably already knew that)

**Comment by desht** [comment]
Yeah the Mk2 creates special "template frame" blocks which are painted with the target block's texture; they're not the real block.  Disguising those might be a challenge, but I will see if it's possible... just not an expert on block rendering I'm afraid...

As for why the extruder can't pick up C&B blocks, see https://github.com/desht/ModularRouters/issues/8.  Basically the NBT seems to change in unpredictable ways, meaning the blocks once broken won't stack with what's already in the router's buffer, so the router can't pull them in.

**Comment by desht** [comment]
OK, Chisel blocks are now supported, both for the Camouflage upgrade and for the Extruder Mk2!  The fix was actually fairly simple once I learned more about rendering layers (and thanks to advice from tterag1098).

C&B support is a different issue, and I don't think there's much else I can do there at this point.
