### ISSUE TITLE
[UX] Termination toggle icon looks like a redstone torch when disabled

### ISSUE THREAD

**Issue by vadcx** [desht/ModularRouters#190]
### Describe the feature

The termination icon should be modified to avoid any possible confusion with a commonly used redstone torch icon.

### Reasons why it should be considered

I've started reading the Modular Routers in-game book where it mentioned the Termination control. I had to look twice or thrice between the book page and the module settings, because (not knowing the mod) it looked like a "disabled redstone torch" to me. It wasn't until I hovered over every single icon that I read the Termination button's title. Only after clicking did I finally found the "T" I was looking for.

Potential icon changes:

1. Remove the red blocker and instead play with "T" colors (for example black-gray)
   - That would be bad for accessibility, players with poor eye sight
2. Replace the red blocker with a red cross, so it does not hide the horizontal line of the capital "T"
3. Replace capital T with a lower-case "t"
4. Redesign the icon and its modes
   - Maybe there are good examples in compsci literature?
   - It's possible to emphasize the process of continuing/stopping in the icon, something like four dots and their colors or a line in between. Example: `∎ ∎ | ∎ ∎` for blocking, the last two dots are red/grey in termination mode. I'm ready to sketch something

### Additional details

Modular routers Termination:
![Screenshot_20230507_121934](https://user-images.githubusercontent.com/129969897/236672043-1b0cb409-201c-4283-8786-3abc7ac92010.png)

Compared to AE2 redstone control icon:
![Screenshot_20230507_122940](https://user-images.githubusercontent.com/129969897/236672205-62dbf059-c3c3-4fef-b610-9d0d46280cae.png)

**Comment by desht** [comment]
@Ridanisaurus thoughts on this?  I can see how the current icon does look a bit similar to a redstone torch...

**Comment by Ridanisaurus** [comment]
I mean at this point any vertical line with red block signal on it would look like a Redstone Torch. But, that been said, I'm always up for a redesign.
I'll look into it tomorrow and will PR an icon update.
