### ISSUE TITLE
Add Delay Module

### ISSUE THREAD

**Issue by k8thekat** [desht/ModularRouters#192]
### Describe the feature

Would be really interesting to have a Module that allows you to delay the next Module by x ticks (which could be set through the module)

### Reasons why it should be considered

Being able to automate Flux Dust creation is one possibility. 

The issue I am having is the Puller Module pulls all the Redstone from a barrel next to it and attempts to "drop" the stack via the Dropper Module, but misses the target because of my subsequent Puller Module that grabs an Obsidian Block and places it in front of the Module Router pushing the redstone mid air off the Flux Block.

I know its possible to add a Redstone Module and have it execute each Module on pulse; but in terms of making a compact design having the ability to "slow down" between Modules would be really useful in allowing other forms of automation.

### Additional details

Now I may be doing this wrong and could possible achieve my desired results with existing modules.

**Comment by desht** [comment]
This isn't really feasible to add, sorry.

However, if you want to ensure that routers run at specified times relative to each other, take a look at the Sync Upgrade.  At its simplest, it's used to ensure routers run at the same time, but it can be used for more than that, and the manual page explains in detail how you can have one router run at a specified time relative to another.
