### ISSUE TITLE
Option to prevent first module execution if last modle has not executed

### ISSUE THREAD

**Issue by Pultex** [desht/ModularRouters#195]
### Describe the feature

Just like the tile have there be a suppression of the first module so it will not activate
until he last module has activated to prevent jamming

also to remove the required IMPLY gate, attached to the first module only, needed to make this effect work without the feature

### Reasons why it should be considered

adds function to make it not need excessive logic added for a simple feature that seem to be partially implemented with the "prevent execution of following module if this module has not executed" toggles already presents 

also makes it move closer to being almost as good as direwolf20's mod "Laser Io"

**Comment by desht** [comment]
That doesn't make any sense.  How can the first module not activate until the last module has activated, when the first module runs before the last one in all cases?

> also makes it move closer to being almost as good as direwolf20's mod "Laser Io"

Gee, thanks /s

**Comment by desht** [comment]
Closing this since it makes no sense.  Feel free to update with clearer explanation of what you need, along with a practical use case, and I'll consider it.
