### ISSUE TITLE
Suggestion: Mekanism Gas Transport

### ISSUE THREAD

**Issue by shanoaice** [desht/ModularRouters#197]
### Describe the feature

Just add a module that allows the router to store and transport Mekanism Gas.

### Reasons why it should be considered

Lots of Mekanism machines simutaneously accepts mutiple kinds of stuff (item, fluid, gas, etc.) which makes compact wiring a huge hassle, even with multifunctional pipes. It would be great to have a wireless transport method to assist Mekanism gameplay.

### Additional details

[Mekanism](https://modrinth.com/mod/mekanism)
Though I am not sure whether this should go into an addon mod.

**Comment by desht** [comment]
Yes, this would be in an addon mod.  I don't plan to add native Gas support to Modular Routers.
