### ISSUE TITLE
[Feature Request] Block Placing with Range >1

### ISSUE THREAD

**Issue by EisigesEis** [desht/ModularRouters#199]
### Describe the feature

Can we have a module which can place blocks in an area further than 1 block away?

### Reasons why it should be considered

I may have overread the feature. For i.e. rituals you have to place blocks in a wide area. I resort to "Block Placer" module, which can only place in a 1-block range. This means some routers only exist for placing one block.
The requested feature would dramatically reduce the number of routers needed for automating a ritual.

### Additional details

I'm not sure what performance impact this feature would have. I'm always open for suggestions or adapting to another mod which already solves this. Thx :).

**Comment by Attack8** [comment]
Have you taken a look at the Extruder module? I assume this is not what you need.

**Comment by desht** [comment]
This isn't something I plan to add, sorry. But you can have this sort of functionality with multiple routers, e.g. a central routers which uses a Distributor module to send to other routers which then place down the block you need.

If you're looking for other mods to do this sort of thing, PneumaticCraft drones might be worth a look?
