### ISSUE TITLE
Inspection Filter - Enchantment not working

### ISSUE THREAD

**Issue by robertmaxton42** [desht/ModularRouters#20]
A whitelist filter on `Enchantment = 0`, `Enchantment < 1`, or `Enchantment <= 0` does not work as expected - a vacuum router will not pick up unenchanted items, for example.

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Fixed, will be in next release for MC 1.10.2 /1.11.2/ 1.12.
