### ISSUE TITLE
Activator module wont work with Awakened supremium watering can

### ISSUE THREAD

**Issue by IWinGames1** [desht/ModularRouters#201]
### Describe the bug

I was able to make this work using a security upgrade in atm 8 but it wont work in atm 9. i tried using the allow fake allies thing in ftb chunks as well but that didnt work and un-claiming my chunks didn't help either

### How to reproduce the bug

I used the setup AlfredGG used for atm 8 with same setup.

### Expected behavior

The waterting can was supposed to be able water the x by x area.

### Which Minecraft version are you using?

1.20

**Comment by desht** [comment]
From a discord conversation a couple of days ago:

![image](https://github.com/desht/ModularRouters/assets/736831/4109b9e7-a7e0-4656-b194-c4971f53eac6)

So check you do have fake players enabled for your claimed chunks.

**Comment by desht** [comment]
I believe ATM9 explicitly disables fake-player usage of watering cans.
