### ISSUE TITLE
Modular router not working

### ISSUE THREAD

**Issue by mattba10** [desht/ModularRouters#204]
### Describe the bug

Trying to use a modular router with a supremum hoe on interact mode. When in void world (atm9 mod) placing a block 1-5 blocks above the router causes the hoe to stop harvesting.
ATM9 Vers. 0.2.9

### How to reproduce the bug

1. place hoe in router
2. interact with crops
3. place block 1-5 spaces above router to cause it to stop work
4. break block above router to make work
5. place block 6 blocks above router and it will be fine

### Expected behavior

should work regardless of block above router

### Additional details

n/a

### Which Minecraft version are you using?

1.20

### Crash log

N/A

**Comment by desht** [comment]
Screenshot of your setup please.

**Comment by mattba10** [comment]
![2023-11-20_16 47 08](https://github.com/desht/ModularRouters/assets/124603841/2dcd87a7-34d4-4dd6-86ce-751f1fd0d133)
![2023-11-20_16 47 11](https://github.com/desht/ModularRouters/assets/124603841/48116f4a-0139-451e-84d4-8088a729f2a8)
![2023-11-20_16 47 04](https://github.com/desht/ModularRouters/assets/124603841/d2f29e9e-6a99-4d6a-9bda-f9c3d4c2950f)

**Comment by desht** [comment]
I need a screenshot of the activator module setup as well

**Comment by desht** [comment]
Closed due to lack of response. In any case, I believe Mystical Agriculture disallows the use of fake players with its tools.
