### ISSUE TITLE
Activator Module in attack mode should use a sword in the buffer slot

### ISSUE THREAD

**Issue by Bendzsike** [desht/ModularRouters#206]
### Describe the feature

I thought it worked like this, but I noticed that it doesn't matter what sword I put in the Buffer slot, it won't do more damage. I somewhat solved this issue with a Security Update, but with that method, it uses the sword the player holds.

### Reasons why it should be considered

It would be really beneficial in automatic mob grinders.

**Comment by desht** [comment]
Unless something's changed, the Activator module does take the weapon in slot into account.  I can clearly remembering dying to a router more than once while testing OP weapons in it :stuck_out_tongue: 

I will check back and make sure it still works.

**Comment by Bendzsike** [comment]
It also made sense to work that way, but for some reason, if I don't have a Security upgrade in the routers, it doesn't attack the mobs. I'm using the latest version of Vault Hunters 3rd Edition.

**Comment by desht** [comment]
Just checking are you in a chunk protected by FTB Chunks?  And if so, is PvP disabled by FTB Chunks for the team? (pvp is an FTB Teams property in recent chunks/teams releases)

**Comment by Bendzsike** [comment]
No, we don't use any form of chunk protection.

**Comment by desht** [comment]
Just tested in my dev instance and the activator is most definitely using the weapon in the router's buffer, as expected.  With an empty buffer, it did half a heart to me, and with an iron sword about 3 hearts (and killed a sheep in two hits).

Security upgrade also worked as expected - if you're permitted by the security upgade, the router won't attack you, but still attacks other entities, including players not on the security upgrade's list.

So I'd guess there's something else in your modpack which is interfering with the router's operation and cancelling the attack attempts, maybe some kind of fake player suppression.  I presume the router has sufficient energy?  (The activator attack mode requires FE by default, not sure if Vault Hunters modified that)

**Comment by Bendzsike** [comment]
Yes, it's hooked up with evergy, I don't think Vault Hunters changed anything. In my testings, without the Security Update, either it doesn't deal damage, or does half a heart damage. 
I tested it with a sword which has Chilling Cloud (which has a % chance to proc on-hit, having a very easy to see visual effect), and the router only managed to proc it, when it had a Security Upgrade and that sword was in my hand.

**Comment by Bendzsike** [comment]
Did a bit more testing right now, if the router doesn't have a sword in it's buffer slot, it will attack, with the expected half a heart damage. If the router has a sword in it's buffer slot, it will refuse to attack at all. When I remove the sword, it will do one single attack with the sword, and then continues to attack for half a heart of damage.

**Comment by Bendzsike** [comment]
This is the router setup
![image](https://github.com/desht/ModularRouters/assets/79306131/0b074ec1-60ad-4845-a3b0-610d37dfe0e3)
and this is the Activator Module setup.
![image](https://github.com/desht/ModularRouters/assets/79306131/e20936fe-d81a-44ce-b6b0-c25f54b1b86e)

And here is the behavior of the router on video.
https://imgur.com/a/KqgSmMl

I would really like to help find the problem, so I'm down for testing anything, I just have no clue what information should I provide.

**Comment by desht** [comment]
Not sure what to say then. I've tested in dev, and in a local dedicated server, and I do not see this behaviour _at all_.  Therefore, I'd say there's something in your pack interfering with this, so I'd just suggest taking it up with the Vault Hunter devs.

**Comment by Bendzsike** [comment]
Understandable, gonna contact them in this regard then. Thank you for your time!

**Comment by desht** [comment]
Hmm, vault hunters is 1.18, isn't it?  That's a not a version I support anymore in any case (I don't even have a MR 1.18 workspace these days).  Simply not enough hours in the day to support multiple versions, I'm afraid.

**Comment by Bendzsike** [comment]
Yes, it's 1.18
