### ISSUE TITLE
Dropper Module issue

### ISSUE THREAD

**Issue by Rithenar** [desht/ModularRouters#210]
### Describe the bug

when you get to the end of a stack in the router buffer, the module will not dispense the last item

### How to reproduce the bug

Put a router with a dropper module with no restrictions (NBT, damage, etc) and set it up Router to work on pulse. The router will dispense all items on the stack except for the last one

### Expected behavior

Dispense all items in buffer

### Which Minecraft version are you using?

1.20

**Comment by desht** [comment]
Nope, sorry, I don't see that behaviour at all.  The Dropper always drops the last item in the buffer for me.

Going to need a more detailed description of your setup. And also, can you reproduce it an instance with just Modular Routers (mods like JEI/Patchouli/etc are ok) ?

**Comment by desht** [comment]
Closed due to lack of response
