### ISSUE TITLE
Crafting Breaker Module on new versions of Modular Routers only crafts Iron Pickaxe version no matter what input Pickaxe is used.

### ISSUE THREAD

**Issue by QuickBASIC** [desht/ModularRouters#214]
### Describe the bug

The breaker module recipe only gives Iron Pickaxe level Breaker Modules, even with Diamond or Netherite Pickaxe in the recipe. Enchants (Silk Touch and Fortune III) don't carry over to the breaker.

### How to reproduce the bug

Craft a breaker module.

### Expected behavior

Breaker module is crafted and has the breaking level and enchants from input Pickaxe.

### Additional details

Note: Bug doesn't exist in modular-routers v1.20.1-12.0.0 version for Forge (not NeoForge). No other versions tested. 

![20240123121855_1](https://github.com/desht/ModularRouters/assets/7226914/aaf3ab5b-ea30-497a-af50-8c6f159656eb)
![20240123121909_1](https://github.com/desht/ModularRouters/assets/7226914/2be29bb3-cc02-4961-bea7-d684bbe48d83)
![20240123121915_1](https://github.com/desht/ModularRouters/assets/7226914/f53a5c52-dbfb-49ef-ac4e-bf0202194d00)
![20240123122003_1](https://github.com/desht/ModularRouters/assets/7226914/d7931eab-c5ad-4bd7-8d5e-56b4b7494dc5)
![20240123122017_1](https://github.com/desht/ModularRouters/assets/7226914/3ac1a146-1c8d-41f3-85a2-35bf62b5d6e4)
![20240123122028_1](https://github.com/desht/ModularRouters/assets/7226914/e378b4fe-1d73-4351-a5d1-1558a2a645ee)

### Which Minecraft version are you using?

1.20

**Comment by desht** [comment]
Fixed in 12.1.1
