### ISSUE TITLE
Add indicator for missing energy required for operation

### ISSUE THREAD

**Issue by johalun** [desht/ModularRouters#217]
### Describe the feature

When a module requires FE to operate, there should be an indicator that will let the player know FE is required for the module to work. 

### Reasons why it should be considered

Attack entity operation requires energy by default. Other operations can be configured to require energy. However, there's no indication show that FE is required and players might be confused wondering why their router doesn't work when they play on a server with custom energy config options.

**Comment by desht** [comment]
Hmm?  You mean this?

![image](https://github.com/desht/ModularRouters/assets/736831/ac86c115-9332-4344-bd9a-bbfd51cd355a)

**Comment by johalun** [comment]
Indeed that shows for the entity attack mode which is enabled by default. However, I have set a FE requirement for right-clicking and breaking and it doesn't show that for those. Edit: I have confirmed in-game that the modules won't do anything without FE supply. Edit 2: I only changed the config server side first. Changing client side also fixed the issue. Is this expected behavior?

**Comment by desht** [comment]
Yeah, it's using common config to set these values so it is intended. The config isn't synced from server to client.

**Comment by johalun** [comment]
Ah so that why the functionality is correct (i.e. for operation it's using server side config), whilst the UI is using client side config? We just have to make sure to keep them in sync then so the players won't get confused why the modules aren't working.

**Comment by desht** [comment]
Yeah, ideally this would be sync'd, but I'd be concerned about breaking backwards compat (moving from common to server config).  Maybe for 1.20.4+ :)
