### ISSUE TITLE
server crash when opening gui for modular router

### ISSUE THREAD

**Issue by alfredhdahl** [desht/ModularRouters#218]
### Describe the bug

played around with MR for a bit, then game crashed. not been able to reproduce

### How to reproduce the bug

opening modular router gui

### Expected behavior

router gui opens

### Which Minecraft version are you using?

1.18 - critical bugs only

### Crash log

https://pastebin.com/LXiwt0tP

**Comment by desht** [comment]
That crash is in AE2 Wireless Terminal Library, not Modular Routers.  Also, it's a client crash, not a server crash.
