### ISSUE TITLE
Redstone Detection & Transmission

### ISSUE THREAD

**Issue by Rectorian** [desht/ModularRouters#219]
### Describe the feature

It would be really cool to see some sort of implementation of a redstone detector and transmitter module.

For example:
A redstone detector module would be able to detect a redstone signal from a bound block at a range. Such as a lever being switched or a button being pressed and then could output a signal on one of its faces or provide a signal to other modules in the router.
Tier 1 would do detection at a shorter range
Tier 2 would do detection at a larger range (infinite?)
Tier 3 could offer some basic logic control like AND, OR, and Toggle. Complex logic would be left to regular redstone or other mods

A redstone transmitter module could work in tandem with the detector to transmit signals at a range with a specific signal strength and specific direction.
Tier 1 would transmit a short range
Tier 2 would transmit long range (infinite?)
Distribution Transmitter module would send a signal to multiple blocks within a certain range

or

Transmitter module transmits a signal to a bound block within a certain range
Channel Transceiver module would send and receive signals on a number defined channel and could control other modules in the router if in receive mode. (A could redstone channel augment that could be directly installed in a module to control it could also be viable)
Distribution Transmitter (Same as above)

### Reasons why it should be considered

Routers are used to move various things (items, fluids, energy, experience) around and adding redstone signaling seems like a logical addition.

I use routers a ton to disguise and hide a lot of pipes and cables in the pretty areas of my bases and being able to control machines, contraptions, and other routers with redstone signals with no obvious wires would be really helpful when working in tight spaces.

**Comment by desht** [comment]
Sorry, too far out of scope for Modular Routers.
