### ISSUE TITLE
[1.21] NeoForge Crash on server startup

### ISSUE THREAD

**Issue by NielsPilgaard** [desht/ModularRouters#229]
### Describe the bug

When I try to start a server with Modular Routers added, it crashes late in the process.

### How to reproduce the bug

1. Make a server with Modular Routers (+dependencies) and NeoForge
2. Start the server
3. Wait

### Expected behavior

For the server to start

### Additional details

The Minecraft version is 1.21, but that is not available in the dropdown below. I have edited the version number after selecting 1.20 😄

Theurgy also crashes on startup on the same instance, mentioning it in case there's a correlation.
https://github.com/klikli-dev/theurgy/issues/186

### Which Minecraft version are you using?

1.21

### Crash log

https://gist.github.com/NielsPilgaard/28f2fabee7f8c7c23c9d36faa8646e65

**Comment by klikli-dev** [comment]
FYI: The first part of the crashlog comes from theurgy (fixed now!) and is unrelated to the Modular Routers creative tab issue. 
MR stuff starts at https://gist.github.com/NielsPilgaard/28f2fabee7f8c7c23c9d36faa8646e65#file-crash-txt-L140

**Comment by desht** [comment]
Yeah, I see what's going on here, will get this sorted.

**Comment by desht** [comment]
Should be fixed in 13.0.1 release

**Comment by NielsPilgaard** [comment]
Thank you kindly 😊
