### ISSUE TITLE
Breaker Duplication Bug

### ISSUE THREAD

**Issue by whitestarx0312** [desht/ModularRouters#23]
MC: 1.12
Forge: forge-14.21.1.2420
Modular Routers: modular-routers-1.12-3.0.0
Issue: When a router breaks a shulker box it leaves the original shulker box on the ground and it creates a brand new (empty) shulker box inside the router's inventory.

**Comment by desht** [comment]
Confirmed

**Comment by desht** [comment]
Modular Routers v3.0.1 just uploaded, should be approved soon.
