### ISSUE TITLE
Neoforge Changes

### ISSUE THREAD

**Issue by Kevin-Marsh** [desht/ModularRouters#231]
### Describe the bug

Neoforge has made a few changes which effect Modular routers. The PlantType system (Iplantable) was replaced and ToolActions was renamed to ItemAbilities. This prevents Modular Routers from functioning on newer Neoforge builds.

### How to reproduce the bug

Try to run on Neoforge 21.0.40+

### Expected behavior

N/A

### Which Minecraft version are you using?

1.21

**Comment by desht** [comment]
Yes, I'm aware. Next Modular Routers release will be built against the latest Neoforge.  Breaking changes happen on a regular basis in Neoforge betas.

**Comment by desht** [comment]
Actually, what is your exact problem here?  Modular Routers doesn't do anything with `PlantType` / `ItemAbilities`, and compiles and runs without issue on latest Neoforge (21.0.43-beta).

**Comment by Kevin-Marsh** [comment]
If it all works then that is great. The mod was flagged by an allthemods team member searching for any mods that could potentially cause issues that had code mentioned in the breaking neoforge changes. There were a number of mods that were preventing testing and updates to new neoforge version that had issues opened to ensure that the devs were aware.

It appears that the pickaxemodule uses toolactions as a check and blockutil uses the iplantable as a check which you are correct shouldn't cause significant issues.

**Comment by desht** [comment]
Yeah, it all works fine, as far as I can tell. Neither `IPlantable` nor `ToolActions` were affected by the changes made in 21.0.40.

**Comment by Kevin-Marsh** [comment]
Hi again. Crafting a breaker module crashes the game when using the newest neoforge. My assumption is due to the toolactions to itemabilities change that I mentioned. I would assume that whatever calls blockutil might also crash.

**Comment by desht** [comment]
Nope, no crashes here making Breaker Modules, on Neo 21.0.52-beta.  Stacktrace please.

**Comment by Kevin-Marsh** [comment]
Basically you place a module and a pickaxe into a crafting grid and it will crash. This has been reported from a few players now. [Here is the crash log,](https://mclo.gs/H3UB3PV)

**Comment by Kevin-Marsh** [comment]
And [here](https://mclo.gs/Ii46HTk) is it reproduced with only modular routers installed.

**Comment by desht** [comment]
OK, yeah, something weird with my dev workspace.  Using 21.0.52, but `ToolActions` is still present.  Probably gradle caching once again...

**Comment by desht** [comment]
Fixed in 13.0.2 release
