### ISSUE TITLE
Vacuum Module with XP Augment doesn't work.

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [desht/ModularRouters#236]
### Describe the bug

Rarely it might have a chance of working, but it just doesnt seem to work to passively pick up exp.

### How to reproduce the bug

Place rotuer down. put vacuum module in with xp augment, setup mob farm around, auto kill, they dont pick up the exp

### Expected behavior

for it to pick up exp and turn them into bottles

### Which Minecraft version are you using?

1.21

**Comment by Toklo23** [comment]
Experiencing the same issue.

**Comment by desht** [comment]
Nope, working fine here. Tested in dev and on dedicated server, router absorbs XP orbs as expected, and creates Bottles o' Enchanting in the buffer, 100% of the time.

**Comment by NJM1564** [comment]
Not working here. Running all the mods 10 pack.

**Comment by desht** [comment]
Tested in dev with Clumps installed, and the router still picks up XP orbs fine. There's clearly some mod in ATM 10 which is messing this up, so I'd suggest taking it up with the modpack author.

Closing this since there isn't a problem with Modular Routers that I can see.

**Comment by NJM1564** [comment]
I found the problem with mine. Conflict with the FTB chunk protection. Will post to them about it. What's the name of the mods fake player?

**Comment by desht** [comment]
You could, but I am one of the maintainers of FTB Chunks, so... :stuck_out_tongue: 

Modular Router's fake player is `[Modular Routers]`.  But it's much safer to just put a Security Upgrade in your router and have it use a fake player with your ID.  Configuring FTB Chunks to allow the fake player makes your claim protection weaker (someone could put a router down on the edge of your chunks and use it to grief you).
