### ISSUE TITLE
NBT filter (subset or exact mode)

### ISSUE THREAD

**Issue by laundmo** [desht/ModularRouters#237]
### Describe the feature

Similar to the existing advanced filter augments, one which can filter by NBT data. Specifically, should allow the user to specify a NBT structure which needs to be a subset or exact copy (button to switch these, subset is default) of the items NBT.

example: if a item contains `{a:"test", b:{c:"something", d:500}}` it could be matched by a subset NBT filter liks this: `{a:"test"}` or like this: `{b:{c:"something"}}`

Subset mode would obviously look whether the filter NBT is contained in the item NBT, while Exact mode would require the item NBT to be exactly the filters NBT, no extra/missing tags.

### Reasons why it should be considered

There are various mods which store things in NBT which may be interesting to filter, like armour tool affixes from Apotheosis or just vanilla enchantments. It would be nice if these could be filtered by this mod.

I'm aware of 2 mods with similar features, each with their downsides:
- Pipez: blocks a block face with its pipe, no advanced behaviour beyond filtering
- Integrated Dynamics: blocks a block face with its pipe, very advanced behaviour possible but everythung beyond a simple filter is incredibly complex to achive, UX wise, as it essentially implements a currying based programming language with individual items as lines of code.

I think Modular Routers is a great balance between supporting complexity and good UX, which is why having the feature here would be great.

### Additional details

To make filtering by NBT even easier, i imagine a slot in the UI where you can extract the NBT of a existing item and remove individual NBT elements to create a filter could be very useful.

It might also be useful to allow for comparison with numerical NBT values, but this could easily get too complex.

**Comment by desht** [comment]
Item NBT is no longer a thing in Minecraft 1.20.6+, and I have no plans to add significant features to any older releases, sorry.

Data component filtering may be a thing in the future, but more likely supported by an addon mod, like [FTB Filter System](https://curseforge.com/minecraft/mc-mods/ftb-filter-system/).

**Comment by laundmo** [comment]
thank you for the response, i wasn't aware of item NBT being removed

**Comment by desht** [comment]
Yeah see https://minecraft.wiki/w/Data_component_format for more info

**Comment by johnfromstatefarm** [comment]
> Yeah see https://minecraft.wiki/w/Data_component_format for more info

NBT data appears to still exist. Pipez supports NBT, I feel like this should still be possible somehow. There's even an NBT editor mod that works in-game (https://www.curseforge.com/minecraft/mc-mods/nbtedit-reborn/files/5500352)

Please revisit this, I'd love to be able to filter out Apotheosis items this way.
