### ISSUE TITLE
Exception while adding particle

### ISSUE THREAD

**Issue by fatyg5** [desht/ModularRouters#24]
### I used an Item Router to make a bridge. I put a few range upgrades and speed upgrades into the router, with the camoflauge upgrade to hide it as Chisel Marble. When I powered the router, however, it began to go across, but then me and my friend crashed with the same crashlog.
[crash-2017-08-27_20.16.04-client.txt](https://github.com/desht/ModularRouters/files/1254810/crash-2017-08-27_20.16.04-client.txt)

**Comment by desht** [comment]
Yeah, I see the problem.  Easy fix.  Should have a new release out in the next day or so.
