### ISSUE TITLE
modular routeur crash the game

### ISSUE THREAD

**Issue by RobinErza** [desht/ModularRouters#243]
### Describe the bug

if u use puller ou pusher in the routeur the game crash

### How to reproduce the bug

take the routeur et place the puller mk1 ou 2 if u look on the routeur , the game freeze and crash

### Expected behavior

pls fixed this big problem i'm using ur mod in the modpack bersera sky
[message.txt](https://github.com/user-attachments/files/16900496/message.txt)

### Which Minecraft version are you using?

1.16 - UNSUPPORTED

### Crash log

https://pastebin.com/xcwDAHdq

**Comment by desht** [comment]
1) 1.16 is unsupported, sorry.

2) This is probably one of many mixins from another mod causing the problem. From your stack trace:

```
at net.minecraft.client.renderer.ItemRenderer.localvar$bbd000$injected(ItemRenderer.java:1541) ~[?:?] 
```

something's changed the value there, and it's not Modular Routers.
