### ISSUE TITLE
ATM 9 Vacuum Module filter doesnt work 

### ISSUE THREAD

**Issue by abdullamu** [desht/ModularRouters#245]
### Describe the bug

When i use filter to pick up one one specific item the module pick up everything regardless of the filter which breaks the setup

### How to reproduce the bug

place module with vacuum module and filter something it will pick up everything

### Expected behavior

To pick up only whitelisted item 

### Which Minecraft version are you using?

1.20.4 - critical bugs only

**Comment by desht** [comment]
1.20.4 is critical fixes only sorry.  Not really a supported version anymore.
