### ISSUE TITLE
Inspection filter doesnt work correctly

### ISSUE THREAD

**Issue by Popchip9** [desht/ModularRouters#248]
### Describe the bug

Inspection filter does not work correctly with durability on craftoria even when set to >0% it does not pull the master miner marid from out of the dimensional mineshaft, however when set to <anything% it will always pull the master miner out no matter what value i input there. I did go and test if it was just the occultism item that was broken and the filter does not work correctly with vanilla tools either. This is on pack version 1.5.0

### How to reproduce the bug

Place modular router have puller mk2 with inspection filter set to whatever durability value you want to test then have it attempt to pull a broken item out of a inventory

### Expected behavior

It should be pulling the item out when below 50% durability if set to <50% in the inspection filter

### Which Minecraft version are you using?

1.21

**Comment by desht** [comment]
What versions of Modular Routers is in the pack?  If it's 13.0.3, update to 13.1.0; there is a fix for Inspection Filters in that release.

**Comment by desht** [comment]
Closed due to lack of response.
