### ISSUE TITLE
Random server crashing

### ISSUE THREAD

**Issue by Akitori** [desht/ModularRouters#25]
1.12 minecraft

forge 1.12 2420

3.02 modular routers 1.12

1. Leave server running with some modular routers running. 
2. Random crash.
3. Repeat infinity.

[crash-2017-09-08_18.01.30-server.txt](https://github.com/desht/ModularRouters/files/1289306/crash-2017-09-08_18.01.30-server.txt)

Not sure why this is happening.

**Comment by desht** [comment]
Looks like a problem trying to place Forestry double half slabs in particular, but I'll do some investigation. Not sure if it's a problem in Modular Routers or in Forestry.

**Comment by desht** [comment]
I don't suppose you know how the router in question was set up at the time of the crash?  It would be really helpful if I knew that.

It seems like the router is trying to place a double slab, which should be impossible under normal circumstances - you can't get a double slab as an item (to put in the router's buffer); they only exist as blocks.

I've added some exception handling code to Modular Routers (3.0.3 release will be uploaded momentarily) to handle that situation, but it'd still be nice to know how it could have happened in the first place...

**Comment by Akitori** [comment]
Yes and i realize it most likely wasn't your fault. My friend was messing with Actually addition's disruptive lens (in short a lens that turns items into other items), and to try to make some items usable, he created a 'nbt clearer' (basically places the item and breaks it). Sorry for all the mess

**Comment by desht** [comment]
No worries, it's always good to account for edge conditions like this.  The 3.0.3 release will simply refuse to place the block where getting the placeable block state throws an exception (like here).  Closing this now.
