### ISSUE TITLE
hide beams and floating items

### ISSUE THREAD

**Issue by Dryelo** [desht/ModularRouters#250]
### Describe the feature

A suggestion for a new upgrade for the routers:
hide the beams and/or items while transferring them.

### Reasons why it should be considered

Mostly aesthetic reasons.
I use this mod a lot and sometimes it looks a bit messy with beams cris-crossing through my base.

### Additional details

Love your mod, cheers!

**Comment by desht** [comment]
Already a thing: add 2 muffler upgrades to the router.
