### ISSUE TITLE
Unable to see/modify transfer rate in Fluid Modules

### ISSUE THREAD

**Issue by MuteTiefling** [desht/ModularRouters#252]
### Describe the bug

Number showing current rate is missing
![image](https://github.com/user-attachments/assets/08faa592-4b3d-42e0-a83f-0ccbbe1db2ed)
And it's not possible to click/interact with this to increase it as in older versions. I tried clicking then shift scrolling anyway but the module stays at 1000mb/operation
![image](https://github.com/user-attachments/assets/945e6d5b-8ff9-4b84-b4df-412e56e6af4e)

### How to reproduce the bug

1. Place router
2. Add Fluid module
3. Attempt to configure rate

### Expected behavior

Value should be shown and should be changeable

### Which Minecraft version are you using?

1.21

**Comment by desht** [comment]
Fixed in 13.2.0
