### ISSUE TITLE
Redstone Signal Distributor Module

### ISSUE THREAD

**Issue by mikuhl-dev** [desht/ModularRouters#259]
### Describe the feature

I would love to be able to power a block (or multiple blocks for a Mk2, and in any dimension for an Mk3) with a Modular Router.

### Reasons why it should be considered

I always wanted a way for a lever to wirelessly light up multiple redstone lamps, without having to wire redstone to each of them, taking up a bunch of space.

### Additional details

Perhaps the Modular Router would clone its redstone strength to the chosen blocks.

**Comment by desht** [comment]
Sorry, that's not something I intend to add. Remotely redstone-powering something isn't really in scope for this mod.
