### ISSUE TITLE
Waila mod dependency is not lowercase

### ISSUE THREAD

**Issue by mezz** [desht/ModularRouters#26]
https://github.com/desht/ModularRouters/blob/5daf541bf274d8340706dc6c3aed4759a514633e/src/main/java/me/desht/modularrouters/ModularRouters.java#L34

Dependencies with uppercase ModIds will not work as intended, since all modIds are lowercase now.

**Comment by desht** [comment]
Oops, you are correct.  I suspect this particular dependency isn't even needed since Modular Routers runs fine with Waila (Hwyla) anyway.

**Comment by desht** [comment]
Fixed in latest build (unreleased as yet)
