### ISSUE TITLE
Suggestion: Activator Module

### ISSUE THREAD

**Issue by 666lumberjack** [desht/ModularRouters#27]
Mentioned this to you on Reddit, but I figured I'd formalize it here as well. Obvious functions include right or left-click with the ability to target any of the four cardinal directions plus up/down, but perhaps you could also have a upgrade module for it that simulates sneaking while clicking as well?

**Comment by desht** [comment]
This is added now.  Sneaking is part of the module (no upgrade needed).  However, I decided not to include left-clicking - breaking blocks is already handled by the Breaker module, and I feel like attacking mobs is getting a bit out of scope for this mod.
