### ISSUE TITLE
Suggestion: Extruder stair rotation

### ISSUE THREAD

**Issue by BeardStroker** [desht/ModularRouters#29]
Minecraft Version 1.12.2
Forge Version: 14.23.1.2556
Mod Version: 1.12.1-3.0.3

I am trying to use the extruder module to make a hidden staircase, but there is no way to choose which way the stairs come out. I remember the drawbridges from tinkers mechworks had a rotation option but it seemed somewhat complicated to implement so i'm not sure if it is possible, but I would absolutely love it if it was possible to choose the rotation for stairs in particular. 

It would definitely make for some interesting possibilities for more complex patterns if stuff like logs, bone blocks and stairs could be rotated.

**Comment by desht** [comment]
In what direction are you trying to place the stairs currently?  In a vertical direction?  In theory when placing blocks, the fake player used faces the same way as the module direction and placed blocks face toward the player (so placing stairs e.g. west *should* have the stair facing east).  In practice this doesn't always work.  I could look at a special "override direction" setting for the module which forces placed blocks to face a certain direction, I suppose.  Though that would only work for blocks with a standard direction property...

**Comment by BeardStroker** [comment]
I am trying to make a stair come out of the floor so yes vertically. When set to "up" at the moment they face the same way as when they come out of the left side. I tried rotating the router but they still face east. Left, right, front and back functions just like you said.

I am not sure if its a feasible solution but maybe when placing stairs upwards they could face away from the front of the block? That's how I assumed it would work initially.

**Comment by desht** [comment]
Actually yes, that would make perfect sense :)

**Comment by desht** [comment]
Implemented in new 3.1.0 release.
