### ISSUE TITLE
Player arm in 1st person transparent

### ISSUE THREAD

**Issue by nanakisan** [desht/ModularRouters#3]
I was wondering what mod was responsible for it. But when a post on the FTB Subreddit came up revealing someone else having the problem. I cross referenced their mod list to my packs own mods. Disabling everything in sequence with your mod being last. When your mod was turned off the arm model was fixed.

**Comment by desht** [comment]
Hmm. Did you have any routers nearby displaying particle effects? That's the only possible explanation I can think of; nothing else in the mod makes OpenGL calls. I'll do some investigation anyway.

**Comment by nanakisan** [comment]
Nope I tested with a fresh world. After disabling the mod the problem went away.

**Comment by desht** [comment]
Yep,  confirmed, my fault. I'll hopefully have a fix out in the next day or two.

**Comment by nanakisan** [comment]
Ahh very good then!

**Comment by desht** [comment]
Fixed in 1.0.3 release, just uploaded to Curseforge.
