### ISSUE TITLE
Vacuum Module GUI incorrectly aligned

### ISSUE THREAD

**Issue by Hjaldar** [desht/ModularRouters#32]
### Minecraft Version

1.12.2

### Forge Version

14.23.1.2598

### Mod Version

Issue present in 1.12.2-3.1.1
Issue NOT present in 1.12.2-3.1.0

### Describe your problem, including steps to reproduce it

Right click a Vacuum Module to open its GUI. The GUI is placed in the top left of the screen rather than being centered. Behavior is independent of GUI scale. The Vacuum Module is the only module with this behavior.

Trying to click in the mis-aligned GUI does not interact correctly with the inventory slots under the mouse, eventually leading to this crash: https://gist.github.com/Hjaldar/245df7909a111d19064f582fb1867cb8

### Any other comments?

Testing environment also included JEI 1.12.2-4.6.5.147.

**Comment by desht** [comment]
Interesting.  This only happens outside the dev environment.  Which might make it hard to debug, but let's see...

**Comment by Hjaldar** [comment]
I also had a different crash in my modpack environment but couldn't reproduce this one in my testing environment. I think I had an item on the mouse at the time and was trying to put it into a GUI slot. While doing this the item picked up by the mouse was not the one under the cursor.

Anyway, here it is in case it is useful: https://gist.github.com/Hjaldar/63e69d90cf4d59a435b570070f0ad245

**Comment by desht** [comment]
Can you try this build: http://jenkins.k-4u.nl/view/Desht/job/ModularRouters/6/artifact/build/libs/modular-routers-1.12.2-3.1.2.jar

and let me know how that's working?

**Comment by desht** [comment]
BTW your second crash should also be resolved by the updated build.

**Comment by calloatti** [comment]
Came here to report exactly this. New world, first router I build, of course I needed an xp vaccum module.

Crash report with all the info:

https://paste.ee/p/uOIfp

**Comment by Hjaldar** [comment]
That build works. The Vacuum Module GUI is now centered correctly and can be interacted with properly, without crashing. A small build using the module also works correctly.

Thank you.

**Comment by calloatti** [comment]
modular-routers-1.12.2-3.1.2 works

**Comment by desht** [comment]
Cool, I'll be doing an official release for that today.

**Comment by desht** [comment]
v3.1.2 is available from Curseforge now.
