### ISSUE TITLE
extruder mk2 mimic issue

### ISSUE THREAD

**Issue by Ezelsorix** [desht/ModularRouters#33]
### Minecraft Version
1.12.2
### Forge Version
14.23.1.2601
### Mod Version
modular-routers-1.12.2-3.1.2
### Describe your problem, including steps to reproduce it
The extruder module mk2 places template blocks that don't mimic the hardness, blast resistance, transparency and redstone behaviour of the original block.
### Any other comments? 
If this seems op without a price, a "mimicry upgrade" might be a good idea. Just a suggestion. For myself  I only need the functionality.

**Comment by desht** [comment]
Yeah, I'm thinking an augment (which goes in the Extruder module) would be necessary here for balance purposes.

**Comment by desht** [comment]
I've added a new augment, to be inserted in the Extruder Mk2 module - the Mimic Augment.  With that inserted, you will get the extended mimicking behaviour you suggested, as well as light emission (e.g. if you extrude fake glowstone blocks, they will glow).

Transparent blocks not working was a bug - some code that I'd neglected to port over from the 1.11.2 version of the mod, where it's always worked.  But that's fixed now, and doesn't require the Mimic Augment.

If you'd like to test this out ahead of the next release, you can get the latest version from http://jenkins.k-4u.nl/view/Desht/job/ModularRouters/ - use build 9 or later.

**Comment by desht** [comment]
Also, I changed explosion handling for routers with installed Blast Upgrades a little - I haven't tested it with nukes (works fine with TNT & creepers), but I'd be interested to know if it makes any difference for you with nuclear explosions.

**Comment by Ezelsorix** [comment]
Sorry it took me so long to reply, I was lost in the forests of medieval bohemia and also had problems updating ftb revelation^^. 

Blast upgrades work now on ic nukes, so do all blocks the mk1 and mk2(with mimic) place: perfect :-) . Also one thing that was fixed along the way it seems: if the extruder collects something like glass it doesn't make a breaking glass sound any more.  
Thank you very much for the incredible support, this is another puzzle piece in porting over to 1.12 from 1.6.4 for me :-) .

**Comment by desht** [comment]
This is now in the 3.1.3 release, just approved.
