### ISSUE TITLE
extruder mk1 "shortcircuiting" router with redstone blocks

### ISSUE THREAD

**Issue by Ezelsorix** [desht/ModularRouters#34]
### Minecraft Version
1.12.2
### Forge Version
14.23.1.2601
### Mod Version
modular-routers-1.12.2-3.1.2
### Describe your problem, including steps to reproduce it
The extruder module mk1 gives the router a redstone signal if I "place" redstone blocks with it and thus the router can't be deactivated/retracted by conventional means any more.
### Any other comments? 
Actually this makes sense, but also it kind of sucks. I have no idea how tinkers mechworks avoided this and still made the redstone blocks work on other adjacent objects, I guess it just ignored any redstone signal from the side it extruded to. Also I'm not sure if in your mod you'd consider this intended behaviour.

**Comment by desht** [comment]
I admit I hadn't considered this originally but it does make sense in an annoying kind of way. Ignoring signals from the extruding side is probably the best option here...

**Comment by desht** [comment]
This is now in the 3.1.3 release, just approved.
