### ISSUE TITLE
Sync upgrade doesn't work

### ISSUE THREAD

**Issue by Aphyxia** [desht/ModularRouters#35]
### Minecraft Version
1.12.2
### Forge Version
1.12.2 - 14.23.2.2624
### Mod Version
modular-routers-1.12.2-3.1.2.jar
### Describe your problem, including steps to reproduce it
Sync upgrade doesn't work. I have five routers with sync upgrades with the same timing. Upon delivering a redstone signal to all of these routers they still operate at a different time.

**Comment by desht** [comment]
Do you have the same number of speed upgrades in each router?

**Comment by Aphyxia** [comment]
Sorry, forgot to mention. Tested with various speed upgrades - all none, all 9. The same result.

Edit: It works while no other mods are installed, so the fault probably lies in another mod. For example I have [OpticManager](https://minecraft.curseforge.com/projects/opticmanager) making the days and nights longer. I don't have time to test this right now but this looks like an incompatibility issue.

**Comment by desht** [comment]
Yeah, I suspect a compatibility issue.  The Sync Upgrades make the routes use the world time (as returned by ``getWorld().getTotalWorldTime()``) to synchronise the routers.  Anything that messes with world times will very likely mess up router sync as well.

It might be possible to work around that, maybe by maintaining an independent tick counter for routers, not sure.  I'll have a play anyway.

**Comment by desht** [comment]
Fixed in 3.1.4 release.
