### ISSUE TITLE
Extruder mk2

### ISSUE THREAD

**Issue by Ceifeire** [desht/ModularRouters#38]
### Describe your problem, including steps to reproduce it
Putting iron bars in with an Extruder MK2 causes purple/black blocks to come out instead. The MK1 puts them out just fine but wont retract them like I want it to.

**Comment by desht** [comment]
Working a lot better now - bars render, and should be connected.  One thing not working well is ambient occlusion, but that's hard to fake.

**Comment by desht** [comment]
Fixed in 3.1.4 release.
