### ISSUE TITLE
Server Crash after inserting Sender mk2

### ISSUE THREAD

**Issue by Yowesephth** [desht/ModularRouters#4]
http://pastebin.com/3TVzYXup

The sender card was crafted from a card that was already configured, if that makes any difference

**Comment by desht** [comment]
Yeah, confirmed.  It'll happen if a Sender Mk2 is inserted before it's been configured for a destination (by shift-right-clicking the target inventory).  Easy fix, will do a 1.0.4 release today.

**Comment by desht** [comment]
Version 1.0.4 uploaded and approved.   Should fix your problem.
