### ISSUE TITLE
Extruder mk1 not working removing blocks

### ISSUE THREAD

**Issue by Ceifeire** [desht/ModularRouters#40]
### Minecraft Version
1.12.2
### Forge Version
14.23.2.2627
### Mod Version
3.1.3
### Describe your problem, including steps to reproduce it
When using a mk1 extruder it will output the blocks when given a redstone signal but will not retract them when that signal is removed. They just get left there
### Any other comments?
Not entirely sure this is a problem or more so me just doing it wrong. I setup a the router with just a mk1 extruder and then set it to respond to a high redstone signal. then put a lever on it to activate it

**Comment by desht** [comment]
Just leave the router in the default "always run" mode. Setting it to run on high will stop it running without a signal. Redstone settings are intended for other modules, they're not really useful for the Extruder.
