### ISSUE TITLE
Augment Duplication Bug

### ISSUE THREAD

**Issue by MasterEnderman** [desht/ModularRouters#42]
### Minecraft Version
1.12.2
### Forge Version
14.23.4.2727
### Mod Version
3.1.5
### Describe your problem, including steps to reproduce it
- Stack two or more Modules together
- open the Module GUI
- put in an Augment of your choice
- close the GUI
- unstack the Modules
- take the Augment out of all the unstacked modules
- Duplicates!

**Comment by desht** [comment]
Ha, yeah.  Didn't think about that!  Easiest fix will be to simply prevent adding (or indeed modifying in any way) the augment itemstacks in the GUI if there's more than one module in the stack.

**Comment by desht** [comment]
Fixed in 3.2.0 release
