### ISSUE TITLE
Breaker Module doesn't drop mined Blocks

### ISSUE THREAD

**Issue by MasterEnderman** [desht/ModularRouters#43]
### Minecraft Version
1.12.2
### Forge Version
14.23.4.2727
### Mod Version
3.1.5
### Describe your problem, including steps to reproduce it
If you try to mine different ores or obsidian the router instantly breaks them, but no drops are created
Instead of breaking these blocks just let them stay in place and let the router ignore them.
Maybe add a Tier 2 Breaker Model, which can break harder blocks like obsidian and such.

**Comment by desht** [comment]
I'm not seeing this behaviour - tested with both obsidian and diamond ore, and in both cases the block was broken, and the drop (obsidian and diamond, respectively) was pulled into the router's buffer as expected.

I suspect some other mod you have installed is intervening, possibly doing something with the HarvestDropsEvent that gets fired when any block is harvested.  Can you reproduce this with just Modular Routers, or at least a minimal mod set?

**Comment by MasterEnderman** [comment]
The reason for this behavior was [Tool Progression](https://minecraft.curseforge.com/projects/tool-progression?gameCategorySlug=mc-mods&projectID=266550). But I don't know if there is something you can do about that...

**Comment by desht** [comment]
I'll take a look at how Tool Progression is intervening and see if there's anything that can be done about it.

**Comment by Ommina** [comment]
A month or so ago, there was a [commit](https://github.com/tyra314/ToolProgression/commit/dc05dc1221d307f0f012a870a9d864f809101462) by Tool Progression affecting fake players that has, for me, solved this issue.  It was released with their version 1.5.5.
