### ISSUE TITLE
Can't open Module Gui in the last router slot

### ISSUE THREAD

**Issue by MasterEnderman** [desht/ModularRouters#44]
### Minecraft Version
1.12.2
### Forge Version
14.23.4.2727
### Mod Version
3.1.5
### Describe your problem, including steps to reproduce it
You can't open a module if you place it in the most right slot. The keybind and middle mouse button won't open it. the other 8 slots work fine.

![image](https://user-images.githubusercontent.com/24524662/42292294-b8856422-7fd1-11e8-899f-80a315ff1474.png)

**Comment by desht** [comment]
Confirmed, and super-simple fix.  Just a case of using ">="  instead of ">".

**Comment by desht** [comment]
Fixed in 3.2.0 release
