### ISSUE TITLE
Filtering issue on the Breaker Module

### ISSUE THREAD

**Issue by BillboardEric** [desht/ModularRouters#45]
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2715

### Mod Version
3.1.5

### Describe your problem, including steps to reproduce it
When setting the breaker module to only break dirt, it will still break grass. I have tried filtering it in different ways like blacklisting grass or whitelisting dirt and still no change.

**Comment by desht** [comment]
Yeah, that's the way it works - by the item that is dropped, not by the block.  One thing that should work is to make it silk touch (craft it with a Silk Touch book); then it will drop grass blocks and the filter should match.

**Comment by BillboardEric** [comment]
Ah ok, I didn't know the filter was by what block is dropped. 
Thank you.
