### ISSUE TITLE
Unbound Puller Module Mk2 crashes the game

### ISSUE THREAD

**Issue by tommyTT** [desht/ModularRouters#46]
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2759

### Mod Version
1.12.2-3.2.0

### Describe your problem, including steps to reproduce it
Game crashes with a NullPointerException when you do the following:
1. Set down a new router.
2. Insert a Puller Module Mk2 without binding it to a target.

### Any other comments?
NPE occurs [here](https://github.com/desht/ModularRouters/blob/MC1.12-master/src/main/java/me/desht/modularrouters/logic/compiled/CompiledPullerModule2.java#L32).
Crash Log [here](https://paste.ee/p/WPg3T).

**Comment by desht** [comment]
Oops, yeah.  Easy fix though.

**Comment by desht** [comment]
I'll do a new release soon, but build 25+ from http://jenkins.k-4u.nl/view/Desht/job/ModularRouters/ should fix this in the meantime.

**Comment by desht** [comment]
Fixed in 3.2.1 release.
