### ISSUE TITLE
Mod in Modpack on Technic Launcher not working (Is not displayed in mods folder)

### ISSUE THREAD

**Issue by DeinAlbtraumTV** [desht/ModularRouters#47]
### Minecraft Version
1.10.2
### Forge Version
1.10.2 - 12.18.3.2511
### Mod Version
1.10.2 - 1.4.2
### Describe your problem, including steps to reproduce it
I wanted do create a Modpack for the Technic Launcher via Solder, but when i download the pack on the newest version and start it, the mod is not displayed as loaded and i can´t find it in the mods folder.

Reproducing:
Just search the Modpack via this : https://www.technicpack.net/modpack/uwm-fantasycraft-test.1295957
Download it and look in the mods folder!
I´ll attach a screenshot of my solder too, so you can see that i added it.
### Any other comments?
I think this is a great mod and want to use it, because it has no RF
 or stuff like that
Pictures:
![bug1](https://user-images.githubusercontent.com/43067468/45219747-3d750b80-b2ac-11e8-85c1-ba34ebbcb9e0.PNG)
![bug2](https://user-images.githubusercontent.com/43067468/45219753-4239bf80-b2ac-11e8-9e94-9f3aac19c956.PNG)

**Comment by desht** [comment]
No idea, sorry.  I don't know anything about how Solder/Technic works internally, but Modular Routers is available on Curseforge just like any other mod.  If Solder has a problem downloading it, sounds like a problem there.  Have you looked at any logs produced by the launcher?

**Comment by DeinAlbtraumTV** [comment]
No, but i will take a look, does the mod needs to be in an extra Folder or just in the mods Folder?

**Comment by DeinAlbtraumTV** [comment]
But i already downloaded the mod, and then, i uploaded it to solder, so there could not be the problem

**Comment by DeinAlbtraumTV** [comment]
I could not find any problems in the Technic Launcher log, must be a problem with solder, i´ll try reupload the mod and try if it works

**Comment by DeinAlbtraumTV** [comment]
I manually downloaded the Mod from Solder and there it works, don´t know what could be the problem

**Comment by desht** [comment]
Yeah, I'm sorry, this is outside my area.  I don't know Solder or Technic and don't really have time to investigate what's going on with it.  The mod's on Curseforge, there's nothing special about it (just goes in the mods folder).

Closing this since it's not a mod issue.
