### ISSUE TITLE
GUI Tooltip Problem

### ISSUE THREAD

**Issue by reserveword** [desht/ModularRouters#48]
### Minecraft Version
1.12.2
### Forge Version
14.23.4.2760
### Mod Version
3.2.0
### Describe your problem, including steps to reproduce it
![image](https://user-images.githubusercontent.com/12995615/45273226-2f113480-b4e4-11e8-8399-f2ac857b241d.png)
This area of GUI is about horizonal degrees, but the title says speed.
### Any other comments?
We're translating it into Chinese when I found it.

**Comment by desht** [comment]
Yeah that should read "Flinger Yaw", thanks for spotting it.
