### ISSUE TITLE
[Feature Request] Option to let Breaker Module break fluids.

### ISSUE THREAD

**Issue by bpwhelan** [desht/ModularRouters#51]
### Describe your problem, including steps to reproduce it

Would be helpful if breaker module could delete fluids as well as break blocks.

### Any other comments?

Would probably be best to give user the option to ban fluids or not, since some may use the routers for cobble/obsidian farms.

**Comment by desht** [comment]
That's what the fluid module is for - you can set it to absorb fluids. So no need for breaker module support for this.
