### ISSUE TITLE
Routers don't work while inside a Minecolony's radius

### ISSUE THREAD

**Issue by a404error** [desht/ModularRouters#52]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2811
### Mod Version
1.12.2-3.2.1
### Describe your problem, including steps to reproduce it
Modular Routers do not go into an 'active' state while inside a Minecolony radius. They work fine (go into an 'active' state if outside a Minecolony radius. When a redstone current is applied, the active value changes from false to true, and when the action is over, goes back to false until the redstone current changes again (button/lever/etc).

In this screenshot, I'm inside a Minecolony, and no matter how many times I hit the lever, the active state stays false/no blocks extruded.
![inside colony not working](https://user-images.githubusercontent.com/25411322/52973206-4b66a680-338b-11e9-9483-220003ca5fbc.png)

When outside a Minecolony, the lever changes the active state as expected and blocks are extruded.
![outside colony working](https://user-images.githubusercontent.com/25411322/52973207-4b66a680-338b-11e9-8c3a-c4810f70fa8f.png)

### Any other comments?
This is a fantastic mod and makes creating large drawbridges and gates a breeze. I hope this is something you might be able to look into, but if not, the workaround would be to use the Minecolony's commands to unclaim any chunks where a Modular Router is located.

**Comment by desht** [comment]
Hmm, is there a way within Minecolonies to permit specific players to do stuff?  Modular Routers uses a fake player called "[Modular Routers]", so perhaps there's a way to add that fake user to Minecolonies?

**Comment by a404error** [comment]
Going through the list of commands on their wiki, and the only one that looked promising was an addOfficer command. I'm not entirely sure what it does, besides maybe give another user certain permissions, but I tried it with [Modular Routers] and then without the brackets, both, without any success. Just gave an invalid argument error. It was worth a shot I guess there.

On maybe a related note... I have a basic drawbridge setup in my world made out of item routers, and I've noticed that a Minecolonies NPC will walk across the routers and all of the blocks extruded but stop at the very last one. It'll just stand there until I nudge it along and then it'll continue like nothing happened. Odd behavior and I can reproduce it every time. Not sure if that could be a clue as to what the issue is.

I'll hop on the Minecolony discord and see if I can find someone else that might've run into the issue and/or hit them up... see if they have any suggestions. I can confirm that unclaiming a Minecolony owned chunk does allow the routers to work again. Anyway, thanks for the quick response!

**Comment by desht** [comment]
No problem. I'll have a play with it when I get a chance too.

I wonder if Minecolonies doesn't like the space and/or square brackets in the fake player name. I could make that a configurable in the mod config...

**Comment by Raleford** [comment]
This appears to work now, the solution of giving the fake player permissions inside the colony was the solution I was looking for and it did work just fine.

**Comment by desht** [comment]
Note that in the latest 7.4.0 release (for 1.16.5), putting a Security Upgrade in the router makes the router's fake player use the Security Upgrade owner's name & UUID.  So routers can now operate as the actual player (as far as the game is concerned) and not need to worry about adding any special names to protection mods such as FTB Chunks.
