### ISSUE TITLE
Puller module with stack upgrade and regular augment doesn't pull enough

### ISSUE THREAD

**Issue by FlyveHest** [desht/ModularRouters#53]
### Minecraft Version
1.12.2

### Forge Version
14.23.5.2815

### Mod Version
1.12.2-3.2.1

### Describe your problem, including steps to reproduce it
I am using a IE metal press, which needs 4 ingots inserted to process a gear correctly.

I have a router setup with 2 stack upgrades (so it pulls 4) and it works as expected when I just use a puller and a dropper, but I wan't to not fill the internal buffer with for instance 3 ingots if I didn't put an amount divisible by 4 in to start with.

So, i've installed a regulator augment, and set it to pull when there are 3 or more, so, if I have understood correctly, it should pull 4 if there are 4 available.

It only pulls a single ingot (down to three in the chest), and then stops processing further.

I would expect the augment to fire when there are 4 ingots available, and then process to its full capabilities, ie. 4 ingots, and not pull a single ingot, and then stop because now the amount is below what the regulator accepts.

**Comment by desht** [comment]
Sorry for the delay, haven't forgotten about this, but just not enough hours in the day right now.

I'll take a look this when I get chance, but it sounds like your expected behaviour should be what happens so there could be a bug there.

**Comment by desht** [comment]
Fixed in 3.2.2 release
