### ISSUE TITLE
Feature Request: AND filtering option for pullers/senders

### ISSUE THREAD

**Issue by nightstick24** [desht/ModularRouters#56]
Loving the mod, it's so utterly perfect I don't know why it isn't in every modpack ever created, it's all the convenience of item pipes without the hassle and lag of running pipes everywhere. I've noticed in my testing that the filtering for Pullers/Senders seems to be OR only, though, which makes some things much more difficult.

For example, you have a chest with some enchanted and unenchanted leather armour.

Case 1:
You use a Puller with just an Inspection Filter set to 'Enchantment != 0' - it should pull all 
the enchanted stuff, and it does perfectly.

Case 2:
You use a Puller with Leather Boots in the first filter slot, set the Puller to ignore Meta/NBT/Oredict, and in the second slot of the puller, like above, an Inspection Filter set to 'Enchantment != 0' - it should pull all the enchanted Leather Boots, however it will pull all the Leather Boots, enchanted or not, and every enchanted item, just like in Case 1. It pulls all Leather Boots regardless of enchantment because boots are in the filter and Meta/NBT is ignored, but it also pulls everything that's enchanted. I assume this is because the filter is looking for Leather Boots OR 'Enchantment != 0' instead of Leather Boots AND 'Enchantment != 0' to get Enchanted Leather Boots only.

Another option in the Puller/Sender to toggle whether filtering is AND/OR would be extremely helpful! Thanks for this awesome mod!

**Comment by desht** [comment]
Hmm, definitely an interesting idea.  This would be a more general toggle in all modules ("Match all filter items" vs. "Match any filter item").  I'll have a think about it.

**Comment by desht** [comment]
Fixed in 6.1.0 release
