### ISSUE TITLE
Module Crashing

### ISSUE THREAD

**Issue by ProfEnd** [desht/ModularRouters#57]
### Minecraft Version
1.14.2

### Forge Version
26.0.63
### Mod Version
1.14.2-5.0.0-1.
### Describe your problem, including steps to reproduce it
When mousing over a module in inventory with info stored in it, the client crashes.
### Any other comments?
Crash Report-https://pastebin.com/4s2dbeMM

**Comment by desht** [comment]
I'll ensure this is fixed for the upcoming 1.14.4 release (I won't be doing another 1.14.2 release, sorry)

**Comment by desht** [comment]
Fixed in 5.1.0 release for 1.14.4.
