### ISSUE TITLE
Distributer crash

### ISSUE THREAD

**Issue by Archesr** [desht/ModularRouters#60]
### Minecraft Version
1.14.4
### Forge Version
28.1.87
### Mod Version
5.1.1-5
### Describe your problem, including steps to reproduce it
EDIT: happens without this mod----This may be a compatibility issue with Torcherino ( https://www.curseforge.com/minecraft/mc-mods/torcherino )----

Using two routers one dispensing charcoal as fuel one dispensing cobblestone to smelt.

i'm guessing the one that is causing the issue is the fuel one because it crashed just as the forges were getting full. But not sure.

### Any other comments?
[crash-2019-11-09_22.39.44-server.txt](https://github.com/desht/ModularRouters/files/3828081/crash-2019-11-09_22.39.44-server.txt)

**Comment by RamenNoodles** [comment]
I'm getting same issue distributing to crushers from silent's mechanisms. 

I created a new world and the distributer was working fine with one crusher not powered.  I added a few more and it seem fine until I added power. I did not wait to fill the added crushers so I couldn't figure out where it crashes exactly.

[crash-2019-11-10_08.49.42-server.txt](https://github.com/desht/ModularRouters/files/3828513/crash-2019-11-10_08.49.42-server.txt)

**Comment by Archesr** [comment]
Confirmed it only happens when the distributor tries to add an item to a full inventory causing the crash. it does not happen to the sender module, maybe its a check for full inventory missing?

Added the edit that states it does happen even without torcherino, i thought that maybe increasing the clock speed caused the crash.

**Comment by desht** [comment]
There will be an update to resolve this problem in the next day or two.

**Comment by desht** [comment]
Fixed in 5.1.2 release.
