### ISSUE TITLE
Send module with no destination crashes and corrupts the world.

### ISSUE THREAD

**Issue by RamenNoodles** [desht/ModularRouters#61]
### Minecraft Version
1.14

### Forge Version
28.1.90

### Mod Version
5.1.1-5

### Describe your problem, including steps to reproduce it
Placing an item in the item routers buffer, then add send mk2 or mk3.

### Any other comments?
I encountered this problem after putting a pull mod that filled the buffer then adding the send mk3 so i can configure it before getting a destination.

**Comment by desht** [comment]
Stack trace,  please.

**Comment by RamenNoodles** [comment]
[crash-2019-11-29_03.38.35-server.txt](https://github.com/desht/ModularRouters/files/3904364/crash-2019-11-29_03.38.35-server.txt)

I don't understand why you would need this, the bug easy to replicate.

**Comment by desht** [comment]
OK, same problem as #60  - there will be an update out in the next day or two to fix that.
