### ISSUE TITLE
strange incompatibility with the Powah mod

### ISSUE THREAD

**Issue by Serzh812** [desht/ModularRouters#63]
minecraft 1.14 forge 28.1.96 mod 5.1.2.7
strange incompatibility with the Powah mod [https://www.curseforge.com/minecraft/mc-mods/powah](url)
 problem with filters, problem with blocks and much more

**Comment by desht** [comment]
I'll need a lot more information than that. Like, what actually happens?

**Comment by Serzh812** [comment]
example
The Breaker Module destroys the mechanism completely. The buffer is empty. On the ground is empty. Blacklist and whitelist filters do not work either

**Comment by desht** [comment]
"mechanism"?  What "mechanism"?  

_Detailed_ instructions on reproducing your reported bugs please, or this issue gets closed.

**Comment by Serzh812** [comment]
video file
[https://mega.nz/#!6lVngaQA!mAGn4AlX8G7NIw4Zsq-m_PfHPCyrGKh92Gd8hJfLLNY](url)
[https://mega.nz/#!yoMTHKRA!a8nVeXPOBki-RpBQr29DeBXCa-skZgDNCvZ1z4UUU-Y](url)

**Comment by desht** [comment]
Looking at https://github.com/zeroneye/Powah/tree/master/src/main/resources/data/powah/loot_tables/blocks I only see loot tables for a few things.  I'm not surprised nothing's dropping.  Would suggest taking this up with the mod dev for Powah.
