### ISSUE TITLE
Feature request: fluid module upgrade for remote fluid transfer

### ISSUE THREAD

**Issue by noobanidus** [desht/ModularRouters#65]
Pretty much as it says on the tin! Basically the Sender II and Sender III modules.

**Comment by desht** [comment]
I'm not sure about a Fluid Module Mk3, for the same reason I'm reluctant to add a Puller Mk3: the ability to pull items/fluids from anywhere in any dimension just feels a little OP (and has serious potential for griefing on a multiplayer server).  I could allow a Fluid Mk3 which sends fluid only, possibly.

Fluid Mk2 is less controversial, though its range might be smaller than a Sender Mk2.

**Comment by noobanidus** [comment]
I'm totally happy with a Fluid Mk2, it just gives me the ability to have one central water source that's transmitting to multiple machines that need water, instead of just adjacent ones.

**Comment by desht** [comment]
This (Fluid Module Mk2) will be in the (imminent) 6.0.0 release for 1.15.2.

**Comment by noobanidus** [comment]
Hooray!

**Comment by desht** [comment]
Added in 6.0.0 release
