### ISSUE TITLE
Mods repost authorization request

### ISSUE THREAD

**Issue by Aemande123** [desht/ModularRouters#68]
Hello there
Your mods are great! can I move your mods to mcbbs?
mcbbs:https://www.mcbbs.net/
mcbbs is the largest minecraft fan forum in China
I am a Chinese localizer of your mods
I will continue to follow up with localization files.

**I will not provide download sources other than Curseforge**

I'm sorry to ask questions here, because of GFW, I cannot register for a twitch account, so I cannot ask questions on Curseforge.

**Comment by desht** [comment]
Hi, I don't have a problem with you hosting this on mcbbs, as long as you provide proper credit.  And yes, providing only Curseforge as a download source is good :)

**Comment by Aemande123** [comment]
> credit

thank you very much !

**Comment by Aemande123** [comment]
> Hi, I don't have a problem with you hosting this on mcbbs, as long as you provide proper credit. And yes, providing only Curseforge as a download source is good :)

thank you very much !
