### ISSUE TITLE
Dupe Bug in Module Upgrades

### ISSUE THREAD

**Issue by kingofaces2** [desht/ModularRouters#69]
### Minecraft Version
1.14.4
### Forge Version
28.1.109
### Mod Version
1.14.4-5.1.2-7
### Describe your problem, including steps to reproduce it
Item Duplication bug
Inside the Item Router, putting in a Dropper Module or any that have an item filter. Opening the module holding right click to drop zero items in the filter then left click holding with the same item removes the item and give it to you.
![dupe](https://user-images.githubusercontent.com/8289241/73488282-43baca80-436e-11ea-87bf-11ce7c5f9a1d.PNG)

**Comment by desht** [comment]
Sorry, you'll need to explain better what you're doing here, I can't reproduce this problem.

**Comment by kingofaces2** [comment]
I made a unlisted video if that will help you. https://youtu.be/r-VvGGS1dig
Left click item in. Right click drag or right click take item out giving you more.

**Comment by desht** [comment]
Yep, I see the problem now - oops.  Easy fix thankfully - you can get v5.1.3 now from CurseForge.

Update: oops, left a debug message in the 5.1.3 release.  Get 5.1.4 when it's there.
