### ISSUE TITLE
activator module

### ISSUE THREAD

**Issue by Serzh812** [desht/ModularRouters#70]
minecraft 1,15,2
forge-1.15.2-31.1.46
modular_routers_1.15.2_6.0.0_14

Filter "activator module" does not work, black and white list, nbt and ......
Mode - right click item in buffer

**Comment by desht** [comment]
Don't really understand what you're trying to do here.  Can you explain exactly what you're trying to do, and what's not working the way you'd expect?

**Comment by Serzh812** [comment]
video
[https://mega.nz/file/n9tXhaJZ#_0y7XFAZSuklOTKrr1y_pv_QR40Bg9T9UROaUtfLWSE](url)

**Comment by desht** [comment]
Link doesn't work.

**Comment by Serzh812** [comment]
copy and paste in a new tab

**Comment by desht** [comment]
OK, that works.

If you just want to place blocks, use the Placer Module - it's what it's for.

Having said that, the Activator Module doesn't currently check the module filter, but I suppose it should.  Will be fixed in the next release.

**Comment by desht** [comment]
Fixed in 6.0.1 release
