### ISSUE TITLE
[1.15.2] Crash with Modular Routers and Project MMO

### ISSUE THREAD

**Issue by realTIMematrix** [desht/ModularRouters#72]
### Minecraft Version
1 .15.2

### Forge Version
 31.1.74

### Mod Version
modular-routers-1.15.2-6.0.1-15.jar
and
Project MMO-1.15-2.29.3.jar

### Describe your problem, including steps to reproduce it
1. Create Modpack with the two mods
2. Load Modpack and make creative world
3. Go to creative tab and **mouse-over** the item `modularrouters:item_router` 
4. Game crashed due to missing tooltip?

### Any other comments?
If you can't reproduce the crash i can send you the log-files. 
I don't know if your mod causes the problem or the mod from https://github.com/Harmonised7/project_mmo

I also create an issue on the other mod page:
https://github.com/Harmonised7/project_mmo/issues/5

tnx

**Comment by desht** [comment]
Crash log, please?

**Comment by realTIMematrix** [comment]
here we go:

[Crash Report](https://pastebin.com/3rXNUJdC)

[Latest.Log](https://pastebin.com/iFULNAbV)

Thank you for your time to investigate

**Comment by desht** [comment]
This is a bug with Project MMO, which should not be passing a null world and blockpos at https://github.com/Harmonised7/project_mmo/blob/master/src/main/java/harmonised/pmmo/events/ClientEventHandler.java#L183

This works for the default method in `Block`, which doesn't change the world/pos, but any overridden method (like the one in Modular Routers) will likely crash.

I can add a null test in my mod which will avoid this particular instance, but the correct fix is for the PMMO author not to be passing null values there.

**Comment by desht** [comment]
You can try build 16 from https://jenkins.k-4u.nl/job/Modular%20Routers%201.14+/ which should fix your problem.

**Comment by realTIMematrix** [comment]
Problem solved with this version. Tnx a lot

**Comment by Harmonised7** [comment]
<3 Apologies for taking so long, Please contact me on Discord next time to get your issue fixed asap!
