### ISSUE TITLE
Feature Request: more options to player module

### ISSUE THREAD

**Issue by DoomSquirter** [desht/ModularRouters#73]
### Minecraft Version
1.15
### Mod Version
modular-routers-1.15.2-6.0.1-15

Would be nice to have more options for player module.  
Main inventory minus the hotbar, basically just the 3x9 inventory

wanted to use this to move items out of my inventory while mining but if I use it, even with filters, I won't have any stone in my hotbar or anything to place blocks, etc.

**Comment by desht** [comment]
Yeah, good idea.

**Comment by desht** [comment]
Fixed in 6.1.0 release
