### ISSUE TITLE
Extruder Mark II deletes blocks

### ISSUE THREAD

**Issue by PongoSapiens** [desht/ModularRouters#74]
### Minecraft Version
1.15.2
### Forge Version
31.1.77
### Mod Version
6.0.1-15
### Describe your problem, including steps to reproduce it
The extruder Mark II deletes *any* blocks in the path of it's extrusion, and I do mean "any", it can delete any type of block, including at least one block type that definitely should not be deleted, and I would argue that deleting blocks is somewhat nasty under any circumstances, although I accept that "you asked for it" is a defense.

**Comment by desht** [comment]
Nasty? Sorry, are you accusing me of doing something malicious here??

A bit more information and bit less accusation would be appreciated here.

**Comment by desht** [comment]
Update: OK, I see what you mean, and that's definitely a bug which will be fixed in the next release.  No nastiness intended.

**Comment by PongoSapiens** [comment]
Apologies, the reference to "nasty" was intended to be light hearted, and it fell flat. Before I tested it in the nether, it had deleted a bunch of blocks from a build my nephew had been working on, and I was trying to make a joke out of that. No offense was intended, although I can see how unfunny it was reading it this morning.

Thanks for the rapid fix, I love the mod, and I'll stop trying to be funny in bug reports.

**Comment by desht** [comment]
No worries, the internet's terrible at conveying intent :)

**Comment by desht** [comment]
Fixed in 6.1.0 release
