### ISSUE TITLE
Fluid Module MK2 crashes server when you use it without binding to water source

### ISSUE THREAD

**Issue by Tander** [desht/ModularRouters#85]
### Minecraft Version
1.15.2

### Forge Version
31.2.33

### Mod Version
6.1.1-19

### Describe your problem, including steps to reproduce it
Place router, place Fluid Module MK2 and bucket (without changing any settings of module or router). Crash.

**Comment by desht** [comment]
Stacktrace please.

**Comment by Tander** [comment]
It's strange you "can't reproduce" it. Here: 
[crash-2020-08-02_18.17.36-server.txt](https://github.com/desht/ModularRouters/files/5059540/crash-2020-08-02_18.17.36-server.txt)

**Comment by desht** [comment]
Strange or not, when I tested it, it didn't crash, just did nothing as I expected.  I'll add a few extra checks though since clearly you're doing something different to me.

**Comment by desht** [comment]
Fixed in 6.1.2 (1.15) and 7.0.1 (1.16)
