### ISSUE TITLE
[1.16.1] Server crash with puller

### ISSUE THREAD

**Issue by WhitePhant0m** [desht/ModularRouters#86]
### Minecraft Version 
1.16.1

### Forge Version 
32.0.106

### Mod Version 
1.16.1-7.0.0-24

### Describe your problem, including steps to reproduce it
Server crashed when I had a puller pull from Industrial Foregoing mob slaughter factory(forgot to change the pull location)
[Crash Log](https://pastebin.com/TW8552Xb)

**Comment by desht** [comment]
Can you give build 27 from https://jenkins.k-4u.nl/job/Modular%20Routers%201.14+/ a go, please, and see if it helps?

If it doesn't, please raise an issue with Industrial Foregoing, because there's no possible way that the slot I'm querying could be >= `getSlots()`.

**Comment by WhitePhant0m** [comment]
I think it fixed it.

**Comment by desht** [comment]
Fixed in 7.0.1 release
