### ISSUE TITLE
[1.12.2] Extruder MK2 Module not retracting

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [desht/ModularRouters#87]
I installed an Extruder MK2 Module into a router in the latest 1.12.2 version and latest Forge version and put a template in. It would extend, but when power was removed, it stayed open. Am I doing something wrong?

**Comment by desht** [comment]
Would need to set your setup since the router is probably still getting powered from somewhere. Bear in mind though that the 1.12.2 I version is out of support these days so I won't be making any code changes.

**Comment by MoonstreamJustNotInSpace** [comment]
It was just a Extruder MK2 extruding 9 dirt blocks upwards, with a lever on the side.

**Comment by MoonstreamJustNotInSpace** [comment]
Is there a setting I have to turn on to make it break blocks?

**Comment by desht** [comment]
> Would need to set your setup since the router is probably still getting powered from somewhere.

**Comment by desht** [comment]
Closed due to lack of response.  Also, I don't support 1.12.2 any more, sorry.
