### ISSUE TITLE
Filling Water Bottles?

### ISSUE THREAD

**Issue by AdamNisbett** [desht/ModularRouters#88]
### Mod Version Enigmatica 6 0.2.14

I've been trying to automate the filling of water bottles using Modular Routers, with no success.  For initial testing I've placed an empty glass bottle in the Item Router's buffer and have tried using both the Fluid Module Mk 1 and the Activator Module (set to right click item in buffer) to fill the bottles but neither have worked.  For the water source, I've both placed the Item Router above a source block of water and next to the sink from Cooking for Blockheads with the appropriate face chosen in each Module.  Using the same process with an empty bucket instead works just fine.  Is this a bug, or is there something about the glass bottle that doesn't allow it to be filled when right clicked using the Item Router like it does when right clicked by the player?

**Comment by desht** [comment]
Not a bug, just simply that water bottles don't provide a fluid handler capability like buckets and most modded tanks do.

However it would be useful functionality, so I could special-case bottles, I guess.

**Comment by AdamNisbett** [comment]
The workaround wasn’t too difficult with the new vanilla Minecraft dispenser functionality - I put down a dispenser facing the water source and then put the item router facing that. Then I put an empty bottle in the dispenser, and the processing chain in the item router was to activate the dispenser using the redstone module, send the new empty bottle from the buffer to the dispenser, then pull the full bottle from the dispenser into the buffer. 

It didn’t surprise me that the fluid module didn’t operate on bottles, but I expected the right clicking of the activator module to fill it given that it describes itself as equivalent to the player right clicking with that object. But yeah, since there’s a reasonably easy work around it’s just up to you as to whether it’s worth the time to add the special case for the sake of it operating intuitively.

**Comment by desht** [comment]
Actually, yeah, the Activator should be able to handle that.  I will take a look into that.

**Comment by desht** [comment]
Fixrd in 7.0.2 release.
