### ISSUE TITLE
Activator module in Activate block mode only works if there is an item in router inventory (any item)

### ISSUE THREAD

**Issue by diegofpais** [desht/ModularRouters#89]
### Any other comments? This is counter intuitive and narrows functionality since it's not possible, for example, harvest a berry and put it in router inventory (it just drops to the ground). Please see attachted clip. Thank you!
[2020-09-17-01-44-171.zip](https://github.com/desht/ModularRouters/files/5236372/2020-09-17-01-44-171.zip)

**Comment by desht** [comment]
Yeah that's a good point. Although your should be able to work around it for now by having some item like a stick in the router, and another router with a vacuum upgrade to pick up drops.

But I can add empty handed clicking easily enough.

**Comment by desht** [comment]
Fixrd in latest release for 1.15.2 and 1.16.1
