### ISSUE TITLE
Activator Module "Look Above" does not function

### ISSUE THREAD

**Issue by papaworld** [desht/ModularRouters#95]
MC: 1.16.3
FML: 34.1.25
Modular Routers: 1.16.3-7.2.0-39

Using Activator Module to plant saplings and apply bonemeal.
Works fine "Look Level" and "Look Below"... but not "Look Above".
Tx

**Comment by desht** [comment]
What's your setup here, exactly?  Can I see screenshots of your router and also of the activator module gui?

**Comment by papaworld** [comment]
Hi, just for a heads up.... I've been using this design sucessfully in 1.12.2, 1.14.x-1.15.x (1.15.2 functioning pix supplied - 1st pix). Replicated these systems in 1.16.3 and does not work. The idea of having 2 activator modules in the router, activator 1 "fertilizer" to grow plant/tree, activator 2 "pop" the mature plant to be picked up via vacuum in another router.

In 1.16.3 "Look Below" and "Look Level" work fine... "Look Above" does not... again, worked great in MC 12, 14 and 15 at any of the three Look Levels.

Tx

![1 15 2 Functioning](https://user-images.githubusercontent.com/50890375/98415735-77382d00-2043-11eb-9ecb-35e2fa9da43c.png)
![1 16 3 Overall](https://user-images.githubusercontent.com/50890375/98415736-78695a00-2043-11eb-8805-f7545a94defc.png)
![2020-11-06_15 04 11](https://user-images.githubusercontent.com/50890375/98415738-7901f080-2043-11eb-84ac-58ed70d61e97.png)
![2020-11-06_15 04 16](https://user-images.githubusercontent.com/50890375/98415739-7901f080-2043-11eb-9b1b-0d3729f37e21.png)
![2020-11-06_15 04 21](https://user-images.githubusercontent.com/50890375/98415741-799a8700-2043-11eb-8d88-2a22a57eac4d.png)
![2020-11-06_15 04 26](https://user-images.githubusercontent.com/50890375/98415744-7a331d80-2043-11eb-9108-86b6782a6f6b.png)
![2020-11-06_15 04 30](https://user-images.githubusercontent.com/50890375/98415748-7a331d80-2043-11eb-9db9-5f4f68067c81.png)
![2020-11-06_15 04 36](https://user-images.githubusercontent.com/50890375/98415749-7acbb400-2043-11eb-9742-916b59d10c0e.png)
![2020-11-06_15 04 43](https://user-images.githubusercontent.com/50890375/98415751-7b644a80-2043-11eb-8481-2d01f7b7d591.png)

**Comment by desht** [comment]
Interesting. I don't *think* I changed anything required to the activator module in 1.16, so I wonder if there's been some subtle vanilla change. I'll look into it anyway.

Update: ah, wait. I did make a change, for more accurate raytracing behaviour from the router fake player to the block being interacted with, which could well break this behaviour since the dirt block would effectively block the fake player's view. Gonna have to figure out a way around this....

**Comment by papaworld** [comment]
If this is helpful... the "fertilizer" router will most of the time fertilize 1 block below when the activator module is set to Look Above. Thanx for looking into this.

**Comment by desht** [comment]
Could you try out build 40 from https://jenkins.k-4u.nl/job/Modular%20Routers%201.14+/ and see if that helps?  In my testing, it covered all the use cases I could think of successfully, but more testing would be appreciated...

**Comment by papaworld** [comment]
The 40 Build worked partially.
Activator Module Modes:
- Bow (Right Click item in Buffer) - Feeds Fertilizer
- Furnace (Activate Block) - "Pops" Mature Plant

Look Above works for stock MineCraft plants - Fertilizes and "Pop"
Look Above does not work for, example, Metal Bushes Mod - will Fertilize, but does not "Pop" (Furnace).

Look Below and Look Level the Activator works fine for both, along with Fertilizing trees and all other applications built.

The Range of Look Level for planting saplings is still 4 saplings in a row, as it has in the past.

BTW: The Vacuum Module works as it should, along with the XP Vacuum Augment (bottles, fluid, buckets), Fast Pickup Augment, Speed Upgrade and Blsast Upgrade.

**Comment by desht** [comment]
Give build 41 a go.. should work fine with Metal Bushes.  I haven't specifically tested with Metal Bushes, but examining the mod shows their bushes are just a subclass of vanilla Sweet Berry Bushes, which are working fine now after the last commit I made.

(By the way, the "furnace" icon is actually a Dispenser :)

**Comment by papaworld** [comment]
Build 41 works great!!! ThanX much for you efforts. Tried many mods involving seeds for plants and saplings for trees, etc... all work as intended.

YES! - I use the Activator for 2x2 infinite water using Router with bucket pickup and dispense into a tank. Also, making obsidian and other items/transfer, a wither wacker for wither roses, XP collection/bottling and Astral Sorcery to place crystals in starlight tanks using the 8-up Module. Been using your mod for a long time (1.12). A superior and very helpful mod that no other mod comes near. Very underrated, but you have a great following.

ThanX again for your attention and diligence.

**Comment by desht** [comment]
Thanks for the kind words :)

**Comment by desht** [comment]
Fixed in 7.3.0 release

**Comment by Spongman** [comment]
maybe it would help if the module indicated somehow what block it was looking at.
