### ISSUE TITLE
Modular routers and claimed chunks

### ISSUE THREAD

**Issue by cornholio84** [desht/ModularRouters#96]
### Minecraft Version
1.16.3
### Forge Version
34.1.25
### Mod Version
modular-routers-1.16.3-7.1.1-37.jar
### Describe your problem, including steps to reproduce it
I just can't get it to work in claimed chunks, even when i invited it as an ally.
Other mods requiring invite works.
I'm also using ATM6 and written there, but i get no response.

thankful for help

**Comment by desht** [comment]
Whatever mod you're using for chunk claiming needs to allow the "[Modular Routers]" fake user.

**Comment by cornholio84** [comment]
Thank you for a quick reply, i will continue my snooping with FTB-Chunks

**Comment by Sintinium** [comment]
Even after adding the [Modular Routers] fake player to my allies in FTB-Chunks it still doesn't work for placing and breaking blocks

**Comment by desht** [comment]
Take it up with FTB chunks. I just use a fake player, I don't do anything special with it. If FTB chunks can't handle that, complain to them.
