### ISSUE TITLE
Feature Request: Pull from multiple inventories

### ISSUE THREAD

**Issue by stragulus** [desht/ModularRouters#97]
### Describe your problem, including steps to reproduce it
There is a module for sending to multiple inventories including round-robin options etc. It would be nice to also be able to pull from multiple inventories using a single pull (tier 3?) module, e.g. when you're distributing the same worload over a bunch of identical machines. Of course it works with 1 pull module per inventory combined in 1 router, but it would be a nice convenience.

### Any other comments?
I may put this in another feature request, but a tool that shows you *all* the nearby router remote inventory connections, not unlike ae2stuff's network monitor, would be very useful!

**Comment by desht** [comment]
A pulling equivalent to the distributor is an idea, yeah.  Need a good name for it...

> a tool that shows you all the nearby router remote inventory connections

Do you mean a way to highlight all nearby routers?

**Comment by stragulus** [comment]
Re tool: It would show all the remote connections from nearby routers. E.g. while playing I hid most of the routers a little out of the way, and it would be nice to see which router pulls from or pushes to which inventory (perhaps even with a white/blacklist item list but that could get messy quick). Roughly similar to the ae2 extra stuff's network visualisation tool that shows the P2P connections.

**Comment by Nonsanity** [comment]
"Puller Module Mk3"? :)

**Comment by desht** [comment]
Problem with that would be confusion with the existing Sender Module Mk3 (i.e. pull from anywhere in any dimension, which I don't really want to add).

This is more like a Distributor Module in reverse, maybe a Collector Module or Gatherer Module?  Though I also don't want to confuse it with the Vacuum Module...

**Comment by desht** [comment]
Thinking about this again, how about just a toggle in the Distributor Module GUI to control sending / pulling?  Default mode would be send, but toggle it to pull from the configured inventories...

**Comment by desht** [comment]
Added in 7.4.0 (as an second mode for the Distributor Module)
