### ISSUE TITLE
Monsters spawning in Template blocks

### ISSUE THREAD

**Issue by IvorAmlug** [desht/ModularRouters#98]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2847
### Mod Version
3.3.0-33
### Describe your problem, including steps to reproduce it
Well so i used the extruder mk2 modules to build gates and for some reason monsters keep spawning in the Template blocks that get placed by the module (monsters spawn anyways even tough i got them disablet but thats probalby an custommobspawner issue)
![2020-12-03_23 50 25](https://user-images.githubusercontent.com/38656481/101098200-d34e8c80-35c2-11eb-967f-def7139416cb.png)
The numbers where from a skeletton
![2020-12-03_23 51 04](https://user-images.githubusercontent.com/38656481/101098264-e9f4e380-35c2-11eb-8869-af57d0ac6e94.png)
A few spiders chilling in my gateway.

**Comment by desht** [comment]
Can you try out build 42 from https://jenkins.k-4u.nl/job/Modular%20Routers%201.14+/ ?

I couldn't make this happen myself, but I've added an explicity disallow for entity spawning in the template frame blocks, hopefully it'll help.

**Comment by desht** [comment]
Oh.  Just realised you're on 1.12.2.  I won't be making any changes for that version, sorry.

**Comment by IvorAmlug** [comment]
might be a CMS (custom mob soawner) bug since it overwrites mobspawns i will try to see if its also with non template blocks spawned by the mk1 module...

**Comment by IvorAmlug** [comment]
Okay deleting custom mob spawner seemed to do the trick
